// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        (unknown)
// source: ArteryControlFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quarantined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *UniqueAddress `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To   *UniqueAddress `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
}

func (x *Quarantined) Reset() {
	*x = Quarantined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quarantined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quarantined) ProtoMessage() {}

func (x *Quarantined) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quarantined.ProtoReflect.Descriptor instead.
func (*Quarantined) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{0}
}

func (x *Quarantined) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Quarantined) GetTo() *UniqueAddress {
	if x != nil {
		return x.To
	}
	return nil
}

// Generic message declaration that is used for all types of message that (currently) have a single
// address field. A message that needs to changed later can be cloned from this one and then adapted.
// ActorSystemTerminating
// ActorSystemTerminating.Ack
// OutboundHandshake.HandshakeRsp
type MessageWithAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *UniqueAddress `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
}

func (x *MessageWithAddress) Reset() {
	*x = MessageWithAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithAddress) ProtoMessage() {}

func (x *MessageWithAddress) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithAddress.ProtoReflect.Descriptor instead.
func (*MessageWithAddress) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithAddress) GetAddress() *UniqueAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type HandshakeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *UniqueAddress `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To   *Address       `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
}

func (x *HandshakeReq) Reset() {
	*x = HandshakeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReq) ProtoMessage() {}

func (x *HandshakeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReq.ProtoReflect.Descriptor instead.
func (*HandshakeReq) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeReq) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *HandshakeReq) GetTo() *Address {
	if x != nil {
		return x.To
	}
	return nil
}

// CompressionProtocol.ActorRefCompressionAdvertisement
// CompressionProtocol.ClassManifestCompressionAdvertisement
type CompressionTableAdvertisement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From         *UniqueAddress `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	OriginUid    *uint64        `protobuf:"varint,2,req,name=originUid" json:"originUid,omitempty"`
	TableVersion *uint32        `protobuf:"varint,3,req,name=tableVersion" json:"tableVersion,omitempty"`
	// actual Map is represented by separate sequences of keys and values,
	// relies on both sequences using the same order so that corresponding entries can be
	// associated again when deserializing
	Keys   []string `protobuf:"bytes,4,rep,name=keys" json:"keys,omitempty"`
	Values []uint32 `protobuf:"varint,5,rep,name=values" json:"values,omitempty"`
}

func (x *CompressionTableAdvertisement) Reset() {
	*x = CompressionTableAdvertisement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressionTableAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressionTableAdvertisement) ProtoMessage() {}

func (x *CompressionTableAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressionTableAdvertisement.ProtoReflect.Descriptor instead.
func (*CompressionTableAdvertisement) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{3}
}

func (x *CompressionTableAdvertisement) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CompressionTableAdvertisement) GetOriginUid() uint64 {
	if x != nil && x.OriginUid != nil {
		return *x.OriginUid
	}
	return 0
}

func (x *CompressionTableAdvertisement) GetTableVersion() uint32 {
	if x != nil && x.TableVersion != nil {
		return *x.TableVersion
	}
	return 0
}

func (x *CompressionTableAdvertisement) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CompressionTableAdvertisement) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// CompressionProtocol.ActorRefCompressionAdvertisementAck
// CompressionProtocol.ClassManifestCompressionAdvertisementAck
type CompressionTableAdvertisementAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    *UniqueAddress `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	Version *uint32        `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
}

func (x *CompressionTableAdvertisementAck) Reset() {
	*x = CompressionTableAdvertisementAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressionTableAdvertisementAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressionTableAdvertisementAck) ProtoMessage() {}

func (x *CompressionTableAdvertisementAck) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressionTableAdvertisementAck.ProtoReflect.Descriptor instead.
func (*CompressionTableAdvertisementAck) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{4}
}

func (x *CompressionTableAdvertisementAck) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CompressionTableAdvertisementAck) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

// SystemMessageDelivery.SystemMessageEnvelope
type SystemMessageEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message         []byte         `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	SerializerId    *int32         `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	MessageManifest []byte         `protobuf:"bytes,3,opt,name=messageManifest" json:"messageManifest,omitempty"`
	SeqNo           *uint64        `protobuf:"varint,4,req,name=seqNo" json:"seqNo,omitempty"`
	AckReplyTo      *UniqueAddress `protobuf:"bytes,5,req,name=ackReplyTo" json:"ackReplyTo,omitempty"`
}

func (x *SystemMessageEnvelope) Reset() {
	*x = SystemMessageEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessageEnvelope) ProtoMessage() {}

func (x *SystemMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessageEnvelope.ProtoReflect.Descriptor instead.
func (*SystemMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{5}
}

func (x *SystemMessageEnvelope) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SystemMessageEnvelope) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *SystemMessageEnvelope) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

func (x *SystemMessageEnvelope) GetSeqNo() uint64 {
	if x != nil && x.SeqNo != nil {
		return *x.SeqNo
	}
	return 0
}

func (x *SystemMessageEnvelope) GetAckReplyTo() *UniqueAddress {
	if x != nil {
		return x.AckReplyTo
	}
	return nil
}

// SystemMessageDelivery.Ack
// SystemMessageDelivery.Nack
type SystemMessageDeliveryAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNo *uint64        `protobuf:"varint,1,req,name=seqNo" json:"seqNo,omitempty"`
	From  *UniqueAddress `protobuf:"bytes,2,req,name=from" json:"from,omitempty"`
}

func (x *SystemMessageDeliveryAck) Reset() {
	*x = SystemMessageDeliveryAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessageDeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessageDeliveryAck) ProtoMessage() {}

func (x *SystemMessageDeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessageDeliveryAck.ProtoReflect.Descriptor instead.
func (*SystemMessageDeliveryAck) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{6}
}

func (x *SystemMessageDeliveryAck) GetSeqNo() uint64 {
	if x != nil && x.SeqNo != nil {
		return *x.SeqNo
	}
	return 0
}

func (x *SystemMessageDeliveryAck) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

// *
// Defines a remote address.
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol *string `protobuf:"bytes,1,req,name=protocol" json:"protocol,omitempty"`
	System   *string `protobuf:"bytes,2,req,name=system" json:"system,omitempty"`
	Hostname *string `protobuf:"bytes,3,req,name=hostname" json:"hostname,omitempty"`
	Port     *uint32 `protobuf:"varint,4,req,name=port" json:"port,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{7}
}

func (x *Address) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *Address) GetSystem() string {
	if x != nil && x.System != nil {
		return *x.System
	}
	return ""
}

func (x *Address) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

// *
// Defines a remote address with uid.
type UniqueAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Uid     *uint64  `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
}

func (x *UniqueAddress) Reset() {
	*x = UniqueAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueAddress) ProtoMessage() {}

func (x *UniqueAddress) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueAddress.ProtoReflect.Descriptor instead.
func (*UniqueAddress) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{8}
}

func (x *UniqueAddress) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UniqueAddress) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

// RemoteWatcher.ArteryHeartbeat is empty array
// RemoteWatcher.ArteryHeartbeatRsp
type ArteryHeartbeatRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
}

func (x *ArteryHeartbeatRsp) Reset() {
	*x = ArteryHeartbeatRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArteryControlFormats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArteryHeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArteryHeartbeatRsp) ProtoMessage() {}

func (x *ArteryHeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ArteryControlFormats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArteryHeartbeatRsp.ProtoReflect.Descriptor instead.
func (*ArteryHeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_ArteryControlFormats_proto_rawDescGZIP(), []int{9}
}

func (x *ArteryHeartbeatRsp) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

var File_ArteryControlFormats_proto protoreflect.FileDescriptor

var file_ArteryControlFormats_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x41, 0x72, 0x74, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0b,
	0x51, 0x75, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x0c,
	0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x84, 0x01, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x11, 0x0a, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x04, 0x12, 0x14, 0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x12, 0x0c, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x12, 0x0e, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x22, 0x51, 0x0a, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0f, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x22, 0x8a, 0x01, 0x0a, 0x15, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0c, 0x12, 0x14, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x12, 0x17, 0x0a, 0x0f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x12, 0x0d, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x04, 0x12, 0x22, 0x0a, 0x0a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x47, 0x0a, 0x18, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x41, 0x63, 0x6b, 0x12, 0x0d, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x04, 0x12, 0x1c, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x4b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x12, 0x0e, 0x0a,
	0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x12, 0x10, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x12,
	0x0c, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x22, 0x37, 0x0a,
	0x0d, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0b, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x22, 0x21, 0x0a, 0x12, 0x41, 0x72, 0x74, 0x65, 0x72, 0x79,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x73, 0x70, 0x12, 0x0b, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x42, 0x0a, 0x48, 0x01, 0x5a, 0x06, 0x2e,
	0x2f, 0x61, 0x6b, 0x6b, 0x61,
}

var (
	file_ArteryControlFormats_proto_rawDescOnce sync.Once
	file_ArteryControlFormats_proto_rawDescData = file_ArteryControlFormats_proto_rawDesc
)

func file_ArteryControlFormats_proto_rawDescGZIP() []byte {
	file_ArteryControlFormats_proto_rawDescOnce.Do(func() {
		file_ArteryControlFormats_proto_rawDescData = protoimpl.X.CompressGZIP(file_ArteryControlFormats_proto_rawDescData)
	})
	return file_ArteryControlFormats_proto_rawDescData
}

var file_ArteryControlFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ArteryControlFormats_proto_goTypes = []interface{}{
	(*Quarantined)(nil),                      // 0: Quarantined
	(*MessageWithAddress)(nil),               // 1: MessageWithAddress
	(*HandshakeReq)(nil),                     // 2: HandshakeReq
	(*CompressionTableAdvertisement)(nil),    // 3: CompressionTableAdvertisement
	(*CompressionTableAdvertisementAck)(nil), // 4: CompressionTableAdvertisementAck
	(*SystemMessageEnvelope)(nil),            // 5: SystemMessageEnvelope
	(*SystemMessageDeliveryAck)(nil),         // 6: SystemMessageDeliveryAck
	(*Address)(nil),                          // 7: Address
	(*UniqueAddress)(nil),                    // 8: UniqueAddress
	(*ArteryHeartbeatRsp)(nil),               // 9: ArteryHeartbeatRsp
}
var file_ArteryControlFormats_proto_depIdxs = []int32{
	8,  // 0: Quarantined.from:type_name -> UniqueAddress
	8,  // 1: Quarantined.to:type_name -> UniqueAddress
	8,  // 2: MessageWithAddress.address:type_name -> UniqueAddress
	8,  // 3: HandshakeReq.from:type_name -> UniqueAddress
	7,  // 4: HandshakeReq.to:type_name -> Address
	8,  // 5: CompressionTableAdvertisement.from:type_name -> UniqueAddress
	8,  // 6: CompressionTableAdvertisementAck.from:type_name -> UniqueAddress
	8,  // 7: SystemMessageEnvelope.ackReplyTo:type_name -> UniqueAddress
	8,  // 8: SystemMessageDeliveryAck.from:type_name -> UniqueAddress
	7,  // 9: UniqueAddress.address:type_name -> Address
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ArteryControlFormats_proto_init() }
func file_ArteryControlFormats_proto_init() {
	if File_ArteryControlFormats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ArteryControlFormats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quarantined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressionTableAdvertisement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressionTableAdvertisementAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessageEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessageDeliveryAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArteryControlFormats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArteryHeartbeatRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ArteryControlFormats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ArteryControlFormats_proto_goTypes,
		DependencyIndexes: file_ArteryControlFormats_proto_depIdxs,
		MessageInfos:      file_ArteryControlFormats_proto_msgTypes,
	}.Build()
	File_ArteryControlFormats_proto = out.File
	file_ArteryControlFormats_proto_rawDesc = nil
	file_ArteryControlFormats_proto_goTypes = nil
	file_ArteryControlFormats_proto_depIdxs = nil
}
