//
// Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ContainerFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatternType int32

const (
	PatternType_PARENT        PatternType = 0
	PatternType_CHILD_NAME    PatternType = 1
	PatternType_CHILD_PATTERN PatternType = 2
)

// Enum value maps for PatternType.
var (
	PatternType_name = map[int32]string{
		0: "PARENT",
		1: "CHILD_NAME",
		2: "CHILD_PATTERN",
	}
	PatternType_value = map[string]int32{
		"PARENT":        0,
		"CHILD_NAME":    1,
		"CHILD_PATTERN": 2,
	}
)

func (x PatternType) Enum() *PatternType {
	p := new(PatternType)
	*p = x
	return p
}

func (x PatternType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternType) Descriptor() protoreflect.EnumDescriptor {
	return file_ContainerFormats_proto_enumTypes[0].Descriptor()
}

func (PatternType) Type() protoreflect.EnumType {
	return &file_ContainerFormats_proto_enumTypes[0]
}

func (x PatternType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PatternType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PatternType(num)
	return nil
}

// Deprecated: Use PatternType.Descriptor instead.
func (PatternType) EnumDescriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{0}
}

type SelectionEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnclosedMessage []byte                 `protobuf:"bytes,1,req,name=enclosedMessage" json:"enclosedMessage,omitempty"`
	SerializerId    *int32                 `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	Pattern         []*Selection           `protobuf:"bytes,3,rep,name=pattern" json:"pattern,omitempty"`
	MessageManifest []byte                 `protobuf:"bytes,4,opt,name=messageManifest" json:"messageManifest,omitempty"`
	WildcardFanOut  *bool                  `protobuf:"varint,5,opt,name=wildcardFanOut" json:"wildcardFanOut,omitempty"` // optional for pre 2.3.4 compatibility
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelectionEnvelope) Reset() {
	*x = SelectionEnvelope{}
	mi := &file_ContainerFormats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionEnvelope) ProtoMessage() {}

func (x *SelectionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionEnvelope.ProtoReflect.Descriptor instead.
func (*SelectionEnvelope) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{0}
}

func (x *SelectionEnvelope) GetEnclosedMessage() []byte {
	if x != nil {
		return x.EnclosedMessage
	}
	return nil
}

func (x *SelectionEnvelope) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *SelectionEnvelope) GetPattern() []*Selection {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *SelectionEnvelope) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

func (x *SelectionEnvelope) GetWildcardFanOut() bool {
	if x != nil && x.WildcardFanOut != nil {
		return *x.WildcardFanOut
	}
	return false
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *PatternType           `protobuf:"varint,1,req,name=type,enum=schedulerx_worker.internal.proto.PatternType" json:"type,omitempty"`
	Matcher       *string                `protobuf:"bytes,2,opt,name=matcher" json:"matcher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_ContainerFormats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{1}
}

func (x *Selection) GetType() PatternType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return PatternType_PARENT
}

func (x *Selection) GetMatcher() string {
	if x != nil && x.Matcher != nil {
		return *x.Matcher
	}
	return ""
}

type Identify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *Payload               `protobuf:"bytes,1,req,name=messageId" json:"messageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identify) Reset() {
	*x = Identify{}
	mi := &file_ContainerFormats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identify) ProtoMessage() {}

func (x *Identify) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identify.ProtoReflect.Descriptor instead.
func (*Identify) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{2}
}

func (x *Identify) GetMessageId() *Payload {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type ActorIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId *Payload               `protobuf:"bytes,1,req,name=correlationId" json:"correlationId,omitempty"`
	Ref           *ActorRef              `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorIdentity) Reset() {
	*x = ActorIdentity{}
	mi := &file_ContainerFormats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorIdentity) ProtoMessage() {}

func (x *ActorIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorIdentity.ProtoReflect.Descriptor instead.
func (*ActorIdentity) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{3}
}

func (x *ActorIdentity) GetCorrelationId() *Payload {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *ActorIdentity) GetRef() *ActorRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ActorRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRef) Reset() {
	*x = ActorRef{}
	mi := &file_ContainerFormats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRef) ProtoMessage() {}

func (x *ActorRef) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRef.ProtoReflect.Descriptor instead.
func (*ActorRef) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{4}
}

func (x *ActorRef) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Payload               `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_ContainerFormats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{5}
}

func (x *Option) GetValue() *Payload {
	if x != nil {
		return x.Value
	}
	return nil
}

type Payload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnclosedMessage []byte                 `protobuf:"bytes,1,req,name=enclosedMessage" json:"enclosedMessage,omitempty"`
	SerializerId    *int32                 `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	MessageManifest []byte                 `protobuf:"bytes,4,opt,name=messageManifest" json:"messageManifest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_ContainerFormats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{6}
}

func (x *Payload) GetEnclosedMessage() []byte {
	if x != nil {
		return x.EnclosedMessage
	}
	return nil
}

func (x *Payload) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *Payload) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

type WatcherHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *uint64                `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatcherHeartbeatResponse) Reset() {
	*x = WatcherHeartbeatResponse{}
	mi := &file_ContainerFormats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatcherHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherHeartbeatResponse) ProtoMessage() {}

func (x *WatcherHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*WatcherHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{7}
}

func (x *WatcherHeartbeatResponse) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

type Throwable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     *string                `protobuf:"bytes,1,req,name=className" json:"className,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Cause         *Payload               `protobuf:"bytes,3,opt,name=cause" json:"cause,omitempty"`
	StackTrace    []*StackTraceElement   `protobuf:"bytes,4,rep,name=stackTrace" json:"stackTrace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Throwable) Reset() {
	*x = Throwable{}
	mi := &file_ContainerFormats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Throwable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Throwable) ProtoMessage() {}

func (x *Throwable) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Throwable.ProtoReflect.Descriptor instead.
func (*Throwable) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{8}
}

func (x *Throwable) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *Throwable) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Throwable) GetCause() *Payload {
	if x != nil {
		return x.Cause
	}
	return nil
}

func (x *Throwable) GetStackTrace() []*StackTraceElement {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

type ThrowableNotSerializable struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           *string                `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	OriginalMessage   *string                `protobuf:"bytes,2,req,name=originalMessage" json:"originalMessage,omitempty"`
	OriginalClassName *string                `protobuf:"bytes,3,req,name=originalClassName" json:"originalClassName,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThrowableNotSerializable) Reset() {
	*x = ThrowableNotSerializable{}
	mi := &file_ContainerFormats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowableNotSerializable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowableNotSerializable) ProtoMessage() {}

func (x *ThrowableNotSerializable) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowableNotSerializable.ProtoReflect.Descriptor instead.
func (*ThrowableNotSerializable) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{9}
}

func (x *ThrowableNotSerializable) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ThrowableNotSerializable) GetOriginalMessage() string {
	if x != nil && x.OriginalMessage != nil {
		return *x.OriginalMessage
	}
	return ""
}

func (x *ThrowableNotSerializable) GetOriginalClassName() string {
	if x != nil && x.OriginalClassName != nil {
		return *x.OriginalClassName
	}
	return ""
}

type ActorInitializationException struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ActorRef              `protobuf:"bytes,1,opt,name=actor" json:"actor,omitempty"`
	Message       *string                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Cause         *Payload               `protobuf:"bytes,3,req,name=cause" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorInitializationException) Reset() {
	*x = ActorInitializationException{}
	mi := &file_ContainerFormats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorInitializationException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorInitializationException) ProtoMessage() {}

func (x *ActorInitializationException) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorInitializationException.ProtoReflect.Descriptor instead.
func (*ActorInitializationException) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{10}
}

func (x *ActorInitializationException) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorInitializationException) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ActorInitializationException) GetCause() *Payload {
	if x != nil {
		return x.Cause
	}
	return nil
}

type StackTraceElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     *string                `protobuf:"bytes,1,req,name=className" json:"className,omitempty"`
	MethodName    *string                `protobuf:"bytes,2,req,name=methodName" json:"methodName,omitempty"`
	FileName      *string                `protobuf:"bytes,3,req,name=fileName" json:"fileName,omitempty"`
	LineNumber    *int32                 `protobuf:"varint,4,req,name=lineNumber" json:"lineNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackTraceElement) Reset() {
	*x = StackTraceElement{}
	mi := &file_ContainerFormats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackTraceElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTraceElement) ProtoMessage() {}

func (x *StackTraceElement) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTraceElement.ProtoReflect.Descriptor instead.
func (*StackTraceElement) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{11}
}

func (x *StackTraceElement) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *StackTraceElement) GetMethodName() string {
	if x != nil && x.MethodName != nil {
		return *x.MethodName
	}
	return ""
}

func (x *StackTraceElement) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *StackTraceElement) GetLineNumber() int32 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

var File_ContainerFormats_proto protoreflect.FileDescriptor

const file_ContainerFormats_proto_rawDesc = "" +
	"\n" +
	"\x16ContainerFormats.proto\x12 schedulerx_worker.internal.proto\"\xfa\x01\n" +
	"\x11SelectionEnvelope\x12(\n" +
	"\x0fenclosedMessage\x18\x01 \x02(\fR\x0fenclosedMessage\x12\"\n" +
	"\fserializerId\x18\x02 \x02(\x05R\fserializerId\x12E\n" +
	"\apattern\x18\x03 \x03(\v2+.schedulerx_worker.internal.proto.SelectionR\apattern\x12(\n" +
	"\x0fmessageManifest\x18\x04 \x01(\fR\x0fmessageManifest\x12&\n" +
	"\x0ewildcardFanOut\x18\x05 \x01(\bR\x0ewildcardFanOut\"h\n" +
	"\tSelection\x12A\n" +
	"\x04type\x18\x01 \x02(\x0e2-.schedulerx_worker.internal.proto.PatternTypeR\x04type\x12\x18\n" +
	"\amatcher\x18\x02 \x01(\tR\amatcher\"S\n" +
	"\bIdentify\x12G\n" +
	"\tmessageId\x18\x01 \x02(\v2).schedulerx_worker.internal.proto.PayloadR\tmessageId\"\x9e\x01\n" +
	"\rActorIdentity\x12O\n" +
	"\rcorrelationId\x18\x01 \x02(\v2).schedulerx_worker.internal.proto.PayloadR\rcorrelationId\x12<\n" +
	"\x03ref\x18\x02 \x01(\v2*.schedulerx_worker.internal.proto.ActorRefR\x03ref\"\x1e\n" +
	"\bActorRef\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\"I\n" +
	"\x06Option\x12?\n" +
	"\x05value\x18\x01 \x01(\v2).schedulerx_worker.internal.proto.PayloadR\x05value\"\x81\x01\n" +
	"\aPayload\x12(\n" +
	"\x0fenclosedMessage\x18\x01 \x02(\fR\x0fenclosedMessage\x12\"\n" +
	"\fserializerId\x18\x02 \x02(\x05R\fserializerId\x12(\n" +
	"\x0fmessageManifest\x18\x04 \x01(\fR\x0fmessageManifest\",\n" +
	"\x18WatcherHeartbeatResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x02(\x04R\x03uid\"\xd9\x01\n" +
	"\tThrowable\x12\x1c\n" +
	"\tclassName\x18\x01 \x02(\tR\tclassName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x05cause\x18\x03 \x01(\v2).schedulerx_worker.internal.proto.PayloadR\x05cause\x12S\n" +
	"\n" +
	"stackTrace\x18\x04 \x03(\v23.schedulerx_worker.internal.proto.StackTraceElementR\n" +
	"stackTrace\"\x8c\x01\n" +
	"\x18ThrowableNotSerializable\x12\x18\n" +
	"\amessage\x18\x01 \x02(\tR\amessage\x12(\n" +
	"\x0foriginalMessage\x18\x02 \x02(\tR\x0foriginalMessage\x12,\n" +
	"\x11originalClassName\x18\x03 \x02(\tR\x11originalClassName\"\xbb\x01\n" +
	"\x1cActorInitializationException\x12@\n" +
	"\x05actor\x18\x01 \x01(\v2*.schedulerx_worker.internal.proto.ActorRefR\x05actor\x12\x18\n" +
	"\amessage\x18\x02 \x02(\tR\amessage\x12?\n" +
	"\x05cause\x18\x03 \x02(\v2).schedulerx_worker.internal.proto.PayloadR\x05cause\"\x8d\x01\n" +
	"\x11StackTraceElement\x12\x1c\n" +
	"\tclassName\x18\x01 \x02(\tR\tclassName\x12\x1e\n" +
	"\n" +
	"methodName\x18\x02 \x02(\tR\n" +
	"methodName\x12\x1a\n" +
	"\bfileName\x18\x03 \x02(\tR\bfileName\x12\x1e\n" +
	"\n" +
	"lineNumber\x18\x04 \x02(\x05R\n" +
	"lineNumber*<\n" +
	"\vPatternType\x12\n" +
	"\n" +
	"\x06PARENT\x10\x00\x12\x0e\n" +
	"\n" +
	"CHILD_NAME\x10\x01\x12\x11\n" +
	"\rCHILD_PATTERN\x10\x02B\n" +
	"H\x01Z\x06./akka"

var (
	file_ContainerFormats_proto_rawDescOnce sync.Once
	file_ContainerFormats_proto_rawDescData []byte
)

func file_ContainerFormats_proto_rawDescGZIP() []byte {
	file_ContainerFormats_proto_rawDescOnce.Do(func() {
		file_ContainerFormats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ContainerFormats_proto_rawDesc), len(file_ContainerFormats_proto_rawDesc)))
	})
	return file_ContainerFormats_proto_rawDescData
}

var file_ContainerFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ContainerFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ContainerFormats_proto_goTypes = []any{
	(PatternType)(0),                     // 0: schedulerx_worker.internal.proto.PatternType
	(*SelectionEnvelope)(nil),            // 1: schedulerx_worker.internal.proto.SelectionEnvelope
	(*Selection)(nil),                    // 2: schedulerx_worker.internal.proto.Selection
	(*Identify)(nil),                     // 3: schedulerx_worker.internal.proto.Identify
	(*ActorIdentity)(nil),                // 4: schedulerx_worker.internal.proto.ActorIdentity
	(*ActorRef)(nil),                     // 5: schedulerx_worker.internal.proto.ActorRef
	(*Option)(nil),                       // 6: schedulerx_worker.internal.proto.Option
	(*Payload)(nil),                      // 7: schedulerx_worker.internal.proto.Payload
	(*WatcherHeartbeatResponse)(nil),     // 8: schedulerx_worker.internal.proto.WatcherHeartbeatResponse
	(*Throwable)(nil),                    // 9: schedulerx_worker.internal.proto.Throwable
	(*ThrowableNotSerializable)(nil),     // 10: schedulerx_worker.internal.proto.ThrowableNotSerializable
	(*ActorInitializationException)(nil), // 11: schedulerx_worker.internal.proto.ActorInitializationException
	(*StackTraceElement)(nil),            // 12: schedulerx_worker.internal.proto.StackTraceElement
}
var file_ContainerFormats_proto_depIdxs = []int32{
	2,  // 0: schedulerx_worker.internal.proto.SelectionEnvelope.pattern:type_name -> schedulerx_worker.internal.proto.Selection
	0,  // 1: schedulerx_worker.internal.proto.Selection.type:type_name -> schedulerx_worker.internal.proto.PatternType
	7,  // 2: schedulerx_worker.internal.proto.Identify.messageId:type_name -> schedulerx_worker.internal.proto.Payload
	7,  // 3: schedulerx_worker.internal.proto.ActorIdentity.correlationId:type_name -> schedulerx_worker.internal.proto.Payload
	5,  // 4: schedulerx_worker.internal.proto.ActorIdentity.ref:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 5: schedulerx_worker.internal.proto.Option.value:type_name -> schedulerx_worker.internal.proto.Payload
	7,  // 6: schedulerx_worker.internal.proto.Throwable.cause:type_name -> schedulerx_worker.internal.proto.Payload
	12, // 7: schedulerx_worker.internal.proto.Throwable.stackTrace:type_name -> schedulerx_worker.internal.proto.StackTraceElement
	5,  // 8: schedulerx_worker.internal.proto.ActorInitializationException.actor:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 9: schedulerx_worker.internal.proto.ActorInitializationException.cause:type_name -> schedulerx_worker.internal.proto.Payload
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ContainerFormats_proto_init() }
func file_ContainerFormats_proto_init() {
	if File_ContainerFormats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ContainerFormats_proto_rawDesc), len(file_ContainerFormats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ContainerFormats_proto_goTypes,
		DependencyIndexes: file_ContainerFormats_proto_depIdxs,
		EnumInfos:         file_ContainerFormats_proto_enumTypes,
		MessageInfos:      file_ContainerFormats_proto_msgTypes,
	}.Build()
	File_ContainerFormats_proto = out.File
	file_ContainerFormats_proto_goTypes = nil
	file_ContainerFormats_proto_depIdxs = nil
}
