// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        (unknown)
// source: ContainerFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatternType int32

const (
	PatternType_PARENT        PatternType = 0
	PatternType_CHILD_NAME    PatternType = 1
	PatternType_CHILD_PATTERN PatternType = 2
)

// Enum value maps for PatternType.
var (
	PatternType_name = map[int32]string{
		0: "PARENT",
		1: "CHILD_NAME",
		2: "CHILD_PATTERN",
	}
	PatternType_value = map[string]int32{
		"PARENT":        0,
		"CHILD_NAME":    1,
		"CHILD_PATTERN": 2,
	}
)

func (x PatternType) Enum() *PatternType {
	p := new(PatternType)
	*p = x
	return p
}

func (x PatternType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternType) Descriptor() protoreflect.EnumDescriptor {
	return file_ContainerFormats_proto_enumTypes[0].Descriptor()
}

func (PatternType) Type() protoreflect.EnumType {
	return &file_ContainerFormats_proto_enumTypes[0]
}

func (x PatternType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PatternType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PatternType(num)
	return nil
}

// Deprecated: Use PatternType.Descriptor instead.
func (PatternType) EnumDescriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{0}
}

type SelectionEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnclosedMessage []byte       `protobuf:"bytes,1,req,name=enclosedMessage" json:"enclosedMessage,omitempty"`
	SerializerId    *int32       `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	Pattern         []*Selection `protobuf:"bytes,3,rep,name=pattern" json:"pattern,omitempty"`
	MessageManifest []byte       `protobuf:"bytes,4,opt,name=messageManifest" json:"messageManifest,omitempty"`
	WildcardFanOut  *bool        `protobuf:"varint,5,opt,name=wildcardFanOut" json:"wildcardFanOut,omitempty"` // optional for pre 2.3.4 compatibility
}

func (x *SelectionEnvelope) Reset() {
	*x = SelectionEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionEnvelope) ProtoMessage() {}

func (x *SelectionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionEnvelope.ProtoReflect.Descriptor instead.
func (*SelectionEnvelope) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{0}
}

func (x *SelectionEnvelope) GetEnclosedMessage() []byte {
	if x != nil {
		return x.EnclosedMessage
	}
	return nil
}

func (x *SelectionEnvelope) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *SelectionEnvelope) GetPattern() []*Selection {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *SelectionEnvelope) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

func (x *SelectionEnvelope) GetWildcardFanOut() bool {
	if x != nil && x.WildcardFanOut != nil {
		return *x.WildcardFanOut
	}
	return false
}

type Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    *PatternType `protobuf:"varint,1,req,name=type,enum=PatternType" json:"type,omitempty"`
	Matcher *string      `protobuf:"bytes,2,opt,name=matcher" json:"matcher,omitempty"`
}

func (x *Selection) Reset() {
	*x = Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{1}
}

func (x *Selection) GetType() PatternType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return PatternType_PARENT
}

func (x *Selection) GetMatcher() string {
	if x != nil && x.Matcher != nil {
		return *x.Matcher
	}
	return ""
}

type Identify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId *Payload `protobuf:"bytes,1,req,name=messageId" json:"messageId,omitempty"`
}

func (x *Identify) Reset() {
	*x = Identify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identify) ProtoMessage() {}

func (x *Identify) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identify.ProtoReflect.Descriptor instead.
func (*Identify) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{2}
}

func (x *Identify) GetMessageId() *Payload {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type ActorIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId *Payload  `protobuf:"bytes,1,req,name=correlationId" json:"correlationId,omitempty"`
	Ref           *ActorRef `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
}

func (x *ActorIdentity) Reset() {
	*x = ActorIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorIdentity) ProtoMessage() {}

func (x *ActorIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorIdentity.ProtoReflect.Descriptor instead.
func (*ActorIdentity) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{3}
}

func (x *ActorIdentity) GetCorrelationId() *Payload {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *ActorIdentity) GetRef() *ActorRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ActorRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
}

func (x *ActorRef) Reset() {
	*x = ActorRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRef) ProtoMessage() {}

func (x *ActorRef) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRef.ProtoReflect.Descriptor instead.
func (*ActorRef) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{4}
}

func (x *ActorRef) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Payload `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{5}
}

func (x *Option) GetValue() *Payload {
	if x != nil {
		return x.Value
	}
	return nil
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnclosedMessage []byte `protobuf:"bytes,1,req,name=enclosedMessage" json:"enclosedMessage,omitempty"`
	SerializerId    *int32 `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	MessageManifest []byte `protobuf:"bytes,4,opt,name=messageManifest" json:"messageManifest,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{6}
}

func (x *Payload) GetEnclosedMessage() []byte {
	if x != nil {
		return x.EnclosedMessage
	}
	return nil
}

func (x *Payload) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *Payload) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

type WatcherHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
}

func (x *WatcherHeartbeatResponse) Reset() {
	*x = WatcherHeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherHeartbeatResponse) ProtoMessage() {}

func (x *WatcherHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*WatcherHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{7}
}

func (x *WatcherHeartbeatResponse) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

type Throwable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName  *string              `protobuf:"bytes,1,req,name=className" json:"className,omitempty"`
	Message    *string              `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Cause      *Payload             `protobuf:"bytes,3,opt,name=cause" json:"cause,omitempty"`
	StackTrace []*StackTraceElement `protobuf:"bytes,4,rep,name=stackTrace" json:"stackTrace,omitempty"`
}

func (x *Throwable) Reset() {
	*x = Throwable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Throwable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Throwable) ProtoMessage() {}

func (x *Throwable) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Throwable.ProtoReflect.Descriptor instead.
func (*Throwable) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{8}
}

func (x *Throwable) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *Throwable) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Throwable) GetCause() *Payload {
	if x != nil {
		return x.Cause
	}
	return nil
}

func (x *Throwable) GetStackTrace() []*StackTraceElement {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

type ThrowableNotSerializable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message           *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	OriginalMessage   *string `protobuf:"bytes,2,req,name=originalMessage" json:"originalMessage,omitempty"`
	OriginalClassName *string `protobuf:"bytes,3,req,name=originalClassName" json:"originalClassName,omitempty"`
}

func (x *ThrowableNotSerializable) Reset() {
	*x = ThrowableNotSerializable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThrowableNotSerializable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowableNotSerializable) ProtoMessage() {}

func (x *ThrowableNotSerializable) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowableNotSerializable.ProtoReflect.Descriptor instead.
func (*ThrowableNotSerializable) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{9}
}

func (x *ThrowableNotSerializable) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ThrowableNotSerializable) GetOriginalMessage() string {
	if x != nil && x.OriginalMessage != nil {
		return *x.OriginalMessage
	}
	return ""
}

func (x *ThrowableNotSerializable) GetOriginalClassName() string {
	if x != nil && x.OriginalClassName != nil {
		return *x.OriginalClassName
	}
	return ""
}

type ActorInitializationException struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor   *ActorRef `protobuf:"bytes,1,opt,name=actor" json:"actor,omitempty"`
	Message *string   `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Cause   *Payload  `protobuf:"bytes,3,req,name=cause" json:"cause,omitempty"`
}

func (x *ActorInitializationException) Reset() {
	*x = ActorInitializationException{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorInitializationException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorInitializationException) ProtoMessage() {}

func (x *ActorInitializationException) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorInitializationException.ProtoReflect.Descriptor instead.
func (*ActorInitializationException) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{10}
}

func (x *ActorInitializationException) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorInitializationException) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ActorInitializationException) GetCause() *Payload {
	if x != nil {
		return x.Cause
	}
	return nil
}

type StackTraceElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName  *string `protobuf:"bytes,1,req,name=className" json:"className,omitempty"`
	MethodName *string `protobuf:"bytes,2,req,name=methodName" json:"methodName,omitempty"`
	FileName   *string `protobuf:"bytes,3,req,name=fileName" json:"fileName,omitempty"`
	LineNumber *int32  `protobuf:"varint,4,req,name=lineNumber" json:"lineNumber,omitempty"`
}

func (x *StackTraceElement) Reset() {
	*x = StackTraceElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ContainerFormats_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackTraceElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTraceElement) ProtoMessage() {}

func (x *StackTraceElement) ProtoReflect() protoreflect.Message {
	mi := &file_ContainerFormats_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTraceElement.ProtoReflect.Descriptor instead.
func (*StackTraceElement) Descriptor() ([]byte, []int) {
	return file_ContainerFormats_proto_rawDescGZIP(), []int{11}
}

func (x *StackTraceElement) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *StackTraceElement) GetMethodName() string {
	if x != nil && x.MethodName != nil {
		return *x.MethodName
	}
	return ""
}

func (x *StackTraceElement) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *StackTraceElement) GetLineNumber() int32 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

var File_ContainerFormats_proto protoreflect.FileDescriptor

var file_ContainerFormats_proto_rawDesc = []byte{
	0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x12, 0x14, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x12, 0x1b, 0x0a,
	0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x0f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x12, 0x16, 0x0a, 0x0e, 0x77, 0x69, 0x6c, 0x64, 0x63, 0x61, 0x72, 0x64, 0x46,
	0x61, 0x6e, 0x4f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x22, 0x38, 0x0a, 0x09, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x22, 0x27, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x48,
	0x0a, 0x0d, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x1f, 0x0a, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x16, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x22, 0x18, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x66, 0x12, 0x0c, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x22, 0x21, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x51, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x17, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x12, 0x14, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x12,
	0x17, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x22, 0x27, 0x0a, 0x18, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0b, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x04, 0x22, 0x70, 0x0a, 0x09, 0x54, 0x68, 0x72, 0x6f, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x11,
	0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x12, 0x17, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x26, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x18, 0x54, 0x68, 0x72, 0x6f, 0x77, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x12, 0x17, 0x0a, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x12, 0x19, 0x0a, 0x11, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x22, 0x62, 0x0a, 0x1c, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x63, 0x65, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x12, 0x0f,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x12,
	0x17, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x60, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x63,
	0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x0a,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x12, 0x12, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x12, 0x10, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x12, 0x12, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x2a, 0x3c, 0x0a, 0x0b, 0x50, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x52,
	0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x5f, 0x4e,
	0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x5f, 0x50,
	0x41, 0x54, 0x54, 0x45, 0x52, 0x4e, 0x10, 0x02, 0x42, 0x0a, 0x48, 0x01, 0x5a, 0x06, 0x2e, 0x2f,
	0x61, 0x6b, 0x6b, 0x61,
}

var (
	file_ContainerFormats_proto_rawDescOnce sync.Once
	file_ContainerFormats_proto_rawDescData = file_ContainerFormats_proto_rawDesc
)

func file_ContainerFormats_proto_rawDescGZIP() []byte {
	file_ContainerFormats_proto_rawDescOnce.Do(func() {
		file_ContainerFormats_proto_rawDescData = protoimpl.X.CompressGZIP(file_ContainerFormats_proto_rawDescData)
	})
	return file_ContainerFormats_proto_rawDescData
}

var file_ContainerFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ContainerFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ContainerFormats_proto_goTypes = []interface{}{
	(PatternType)(0),                     // 0: PatternType
	(*SelectionEnvelope)(nil),            // 1: SelectionEnvelope
	(*Selection)(nil),                    // 2: Selection
	(*Identify)(nil),                     // 3: Identify
	(*ActorIdentity)(nil),                // 4: ActorIdentity
	(*ActorRef)(nil),                     // 5: ActorRef
	(*Option)(nil),                       // 6: Option
	(*Payload)(nil),                      // 7: Payload
	(*WatcherHeartbeatResponse)(nil),     // 8: WatcherHeartbeatResponse
	(*Throwable)(nil),                    // 9: Throwable
	(*ThrowableNotSerializable)(nil),     // 10: ThrowableNotSerializable
	(*ActorInitializationException)(nil), // 11: ActorInitializationException
	(*StackTraceElement)(nil),            // 12: StackTraceElement
}
var file_ContainerFormats_proto_depIdxs = []int32{
	2,  // 0: SelectionEnvelope.pattern:type_name -> Selection
	0,  // 1: Selection.type:type_name -> PatternType
	7,  // 2: Identify.messageId:type_name -> Payload
	7,  // 3: ActorIdentity.correlationId:type_name -> Payload
	5,  // 4: ActorIdentity.ref:type_name -> ActorRef
	7,  // 5: Option.value:type_name -> Payload
	7,  // 6: Throwable.cause:type_name -> Payload
	12, // 7: Throwable.stackTrace:type_name -> StackTraceElement
	5,  // 8: ActorInitializationException.actor:type_name -> ActorRef
	7,  // 9: ActorInitializationException.cause:type_name -> Payload
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ContainerFormats_proto_init() }
func file_ContainerFormats_proto_init() {
	if File_ContainerFormats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ContainerFormats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherHeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Throwable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThrowableNotSerializable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorInitializationException); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ContainerFormats_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackTraceElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ContainerFormats_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ContainerFormats_proto_goTypes,
		DependencyIndexes: file_ContainerFormats_proto_depIdxs,
		EnumInfos:         file_ContainerFormats_proto_enumTypes,
		MessageInfos:      file_ContainerFormats_proto_msgTypes,
	}.Build()
	File_ContainerFormats_proto = out.File
	file_ContainerFormats_proto_rawDesc = nil
	file_ContainerFormats_proto_goTypes = nil
	file_ContainerFormats_proto_depIdxs = nil
}
