//
// Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: SystemMessageFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemMessage_Type int32

const (
	SystemMessage_CREATE                  SystemMessage_Type = 0
	SystemMessage_RECREATE                SystemMessage_Type = 1
	SystemMessage_SUSPEND                 SystemMessage_Type = 2
	SystemMessage_RESUME                  SystemMessage_Type = 3
	SystemMessage_TERMINATE               SystemMessage_Type = 4
	SystemMessage_SUPERVISE               SystemMessage_Type = 5
	SystemMessage_WATCH                   SystemMessage_Type = 6
	SystemMessage_UNWATCH                 SystemMessage_Type = 7
	SystemMessage_FAILED                  SystemMessage_Type = 8
	SystemMessage_DEATHWATCH_NOTIFICATION SystemMessage_Type = 9
)

// Enum value maps for SystemMessage_Type.
var (
	SystemMessage_Type_name = map[int32]string{
		0: "CREATE",
		1: "RECREATE",
		2: "SUSPEND",
		3: "RESUME",
		4: "TERMINATE",
		5: "SUPERVISE",
		6: "WATCH",
		7: "UNWATCH",
		8: "FAILED",
		9: "DEATHWATCH_NOTIFICATION",
	}
	SystemMessage_Type_value = map[string]int32{
		"CREATE":                  0,
		"RECREATE":                1,
		"SUSPEND":                 2,
		"RESUME":                  3,
		"TERMINATE":               4,
		"SUPERVISE":               5,
		"WATCH":                   6,
		"UNWATCH":                 7,
		"FAILED":                  8,
		"DEATHWATCH_NOTIFICATION": 9,
	}
)

func (x SystemMessage_Type) Enum() *SystemMessage_Type {
	p := new(SystemMessage_Type)
	*p = x
	return p
}

func (x SystemMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_SystemMessageFormats_proto_enumTypes[0].Descriptor()
}

func (SystemMessage_Type) Type() protoreflect.EnumType {
	return &file_SystemMessageFormats_proto_enumTypes[0]
}

func (x SystemMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SystemMessage_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SystemMessage_Type(num)
	return nil
}

// Deprecated: Use SystemMessage_Type.Descriptor instead.
func (SystemMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{0, 0}
}

type SystemMessage struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Type               *SystemMessage_Type         `protobuf:"varint,1,req,name=type,enum=schedulerx_worker.internal.proto.SystemMessage_Type" json:"type,omitempty"`
	WatchData          *WatchData                  `protobuf:"bytes,2,opt,name=watchData" json:"watchData,omitempty"`
	CauseData          *Payload                    `protobuf:"bytes,3,opt,name=causeData" json:"causeData,omitempty"`
	SuperviseData      *SuperviseData              `protobuf:"bytes,5,opt,name=superviseData" json:"superviseData,omitempty"`
	FailedData         *FailedData                 `protobuf:"bytes,6,opt,name=failedData" json:"failedData,omitempty"`
	DwNotificationData *DeathWatchNotificationData `protobuf:"bytes,7,opt,name=dwNotificationData" json:"dwNotificationData,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	mi := &file_SystemMessageFormats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMessage) GetType() SystemMessage_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SystemMessage_CREATE
}

func (x *SystemMessage) GetWatchData() *WatchData {
	if x != nil {
		return x.WatchData
	}
	return nil
}

func (x *SystemMessage) GetCauseData() *Payload {
	if x != nil {
		return x.CauseData
	}
	return nil
}

func (x *SystemMessage) GetSuperviseData() *SuperviseData {
	if x != nil {
		return x.SuperviseData
	}
	return nil
}

func (x *SystemMessage) GetFailedData() *FailedData {
	if x != nil {
		return x.FailedData
	}
	return nil
}

func (x *SystemMessage) GetDwNotificationData() *DeathWatchNotificationData {
	if x != nil {
		return x.DwNotificationData
	}
	return nil
}

type WatchData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watchee       *ActorRef              `protobuf:"bytes,1,req,name=watchee" json:"watchee,omitempty"`
	Watcher       *ActorRef              `protobuf:"bytes,2,req,name=watcher" json:"watcher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchData) Reset() {
	*x = WatchData{}
	mi := &file_SystemMessageFormats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchData) ProtoMessage() {}

func (x *WatchData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchData.ProtoReflect.Descriptor instead.
func (*WatchData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{1}
}

func (x *WatchData) GetWatchee() *ActorRef {
	if x != nil {
		return x.Watchee
	}
	return nil
}

func (x *WatchData) GetWatcher() *ActorRef {
	if x != nil {
		return x.Watcher
	}
	return nil
}

type SuperviseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *ActorRef              `protobuf:"bytes,1,req,name=child" json:"child,omitempty"`
	Async         *bool                  `protobuf:"varint,2,req,name=async" json:"async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuperviseData) Reset() {
	*x = SuperviseData{}
	mi := &file_SystemMessageFormats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuperviseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperviseData) ProtoMessage() {}

func (x *SuperviseData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperviseData.ProtoReflect.Descriptor instead.
func (*SuperviseData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{2}
}

func (x *SuperviseData) GetChild() *ActorRef {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *SuperviseData) GetAsync() bool {
	if x != nil && x.Async != nil {
		return *x.Async
	}
	return false
}

type FailedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *ActorRef              `protobuf:"bytes,1,req,name=child" json:"child,omitempty"`
	Uid           *uint64                `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedData) Reset() {
	*x = FailedData{}
	mi := &file_SystemMessageFormats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedData) ProtoMessage() {}

func (x *FailedData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedData.ProtoReflect.Descriptor instead.
func (*FailedData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{3}
}

func (x *FailedData) GetChild() *ActorRef {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *FailedData) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

type DeathWatchNotificationData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Actor              *ActorRef              `protobuf:"bytes,1,req,name=actor" json:"actor,omitempty"`
	ExistenceConfirmed *bool                  `protobuf:"varint,2,req,name=existenceConfirmed" json:"existenceConfirmed,omitempty"`
	AddressTerminated  *bool                  `protobuf:"varint,3,req,name=addressTerminated" json:"addressTerminated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeathWatchNotificationData) Reset() {
	*x = DeathWatchNotificationData{}
	mi := &file_SystemMessageFormats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathWatchNotificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathWatchNotificationData) ProtoMessage() {}

func (x *DeathWatchNotificationData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathWatchNotificationData.ProtoReflect.Descriptor instead.
func (*DeathWatchNotificationData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{4}
}

func (x *DeathWatchNotificationData) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DeathWatchNotificationData) GetExistenceConfirmed() bool {
	if x != nil && x.ExistenceConfirmed != nil {
		return *x.ExistenceConfirmed
	}
	return false
}

func (x *DeathWatchNotificationData) GetAddressTerminated() bool {
	if x != nil && x.AddressTerminated != nil {
		return *x.AddressTerminated
	}
	return false
}

var File_SystemMessageFormats_proto protoreflect.FileDescriptor

const file_SystemMessageFormats_proto_rawDesc = "" +
	"\n" +
	"\x1aSystemMessageFormats.proto\x12 schedulerx_worker.internal.proto\x1a\x16ContainerFormats.proto\"\x9b\x05\n" +
	"\rSystemMessage\x12H\n" +
	"\x04type\x18\x01 \x02(\x0e24.schedulerx_worker.internal.proto.SystemMessage.TypeR\x04type\x12I\n" +
	"\twatchData\x18\x02 \x01(\v2+.schedulerx_worker.internal.proto.WatchDataR\twatchData\x12G\n" +
	"\tcauseData\x18\x03 \x01(\v2).schedulerx_worker.internal.proto.PayloadR\tcauseData\x12U\n" +
	"\rsuperviseData\x18\x05 \x01(\v2/.schedulerx_worker.internal.proto.SuperviseDataR\rsuperviseData\x12L\n" +
	"\n" +
	"failedData\x18\x06 \x01(\v2,.schedulerx_worker.internal.proto.FailedDataR\n" +
	"failedData\x12l\n" +
	"\x12dwNotificationData\x18\a \x01(\v2<.schedulerx_worker.internal.proto.DeathWatchNotificationDataR\x12dwNotificationData\"\x98\x01\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\f\n" +
	"\bRECREATE\x10\x01\x12\v\n" +
	"\aSUSPEND\x10\x02\x12\n" +
	"\n" +
	"\x06RESUME\x10\x03\x12\r\n" +
	"\tTERMINATE\x10\x04\x12\r\n" +
	"\tSUPERVISE\x10\x05\x12\t\n" +
	"\x05WATCH\x10\x06\x12\v\n" +
	"\aUNWATCH\x10\a\x12\n" +
	"\n" +
	"\x06FAILED\x10\b\x12\x1b\n" +
	"\x17DEATHWATCH_NOTIFICATION\x10\t\"\x97\x01\n" +
	"\tWatchData\x12D\n" +
	"\awatchee\x18\x01 \x02(\v2*.schedulerx_worker.internal.proto.ActorRefR\awatchee\x12D\n" +
	"\awatcher\x18\x02 \x02(\v2*.schedulerx_worker.internal.proto.ActorRefR\awatcher\"g\n" +
	"\rSuperviseData\x12@\n" +
	"\x05child\x18\x01 \x02(\v2*.schedulerx_worker.internal.proto.ActorRefR\x05child\x12\x14\n" +
	"\x05async\x18\x02 \x02(\bR\x05async\"`\n" +
	"\n" +
	"FailedData\x12@\n" +
	"\x05child\x18\x01 \x02(\v2*.schedulerx_worker.internal.proto.ActorRefR\x05child\x12\x10\n" +
	"\x03uid\x18\x02 \x02(\x04R\x03uid\"\xbc\x01\n" +
	"\x1aDeathWatchNotificationData\x12@\n" +
	"\x05actor\x18\x01 \x02(\v2*.schedulerx_worker.internal.proto.ActorRefR\x05actor\x12.\n" +
	"\x12existenceConfirmed\x18\x02 \x02(\bR\x12existenceConfirmed\x12,\n" +
	"\x11addressTerminated\x18\x03 \x02(\bR\x11addressTerminatedB\n" +
	"H\x01Z\x06./akka"

var (
	file_SystemMessageFormats_proto_rawDescOnce sync.Once
	file_SystemMessageFormats_proto_rawDescData []byte
)

func file_SystemMessageFormats_proto_rawDescGZIP() []byte {
	file_SystemMessageFormats_proto_rawDescOnce.Do(func() {
		file_SystemMessageFormats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SystemMessageFormats_proto_rawDesc), len(file_SystemMessageFormats_proto_rawDesc)))
	})
	return file_SystemMessageFormats_proto_rawDescData
}

var file_SystemMessageFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SystemMessageFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_SystemMessageFormats_proto_goTypes = []any{
	(SystemMessage_Type)(0),            // 0: schedulerx_worker.internal.proto.SystemMessage.Type
	(*SystemMessage)(nil),              // 1: schedulerx_worker.internal.proto.SystemMessage
	(*WatchData)(nil),                  // 2: schedulerx_worker.internal.proto.WatchData
	(*SuperviseData)(nil),              // 3: schedulerx_worker.internal.proto.SuperviseData
	(*FailedData)(nil),                 // 4: schedulerx_worker.internal.proto.FailedData
	(*DeathWatchNotificationData)(nil), // 5: schedulerx_worker.internal.proto.DeathWatchNotificationData
	(*Payload)(nil),                    // 6: schedulerx_worker.internal.proto.Payload
	(*ActorRef)(nil),                   // 7: schedulerx_worker.internal.proto.ActorRef
}
var file_SystemMessageFormats_proto_depIdxs = []int32{
	0,  // 0: schedulerx_worker.internal.proto.SystemMessage.type:type_name -> schedulerx_worker.internal.proto.SystemMessage.Type
	2,  // 1: schedulerx_worker.internal.proto.SystemMessage.watchData:type_name -> schedulerx_worker.internal.proto.WatchData
	6,  // 2: schedulerx_worker.internal.proto.SystemMessage.causeData:type_name -> schedulerx_worker.internal.proto.Payload
	3,  // 3: schedulerx_worker.internal.proto.SystemMessage.superviseData:type_name -> schedulerx_worker.internal.proto.SuperviseData
	4,  // 4: schedulerx_worker.internal.proto.SystemMessage.failedData:type_name -> schedulerx_worker.internal.proto.FailedData
	5,  // 5: schedulerx_worker.internal.proto.SystemMessage.dwNotificationData:type_name -> schedulerx_worker.internal.proto.DeathWatchNotificationData
	7,  // 6: schedulerx_worker.internal.proto.WatchData.watchee:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 7: schedulerx_worker.internal.proto.WatchData.watcher:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 8: schedulerx_worker.internal.proto.SuperviseData.child:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 9: schedulerx_worker.internal.proto.FailedData.child:type_name -> schedulerx_worker.internal.proto.ActorRef
	7,  // 10: schedulerx_worker.internal.proto.DeathWatchNotificationData.actor:type_name -> schedulerx_worker.internal.proto.ActorRef
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_SystemMessageFormats_proto_init() }
func file_SystemMessageFormats_proto_init() {
	if File_SystemMessageFormats_proto != nil {
		return
	}
	file_ContainerFormats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SystemMessageFormats_proto_rawDesc), len(file_SystemMessageFormats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SystemMessageFormats_proto_goTypes,
		DependencyIndexes: file_SystemMessageFormats_proto_depIdxs,
		EnumInfos:         file_SystemMessageFormats_proto_enumTypes,
		MessageInfos:      file_SystemMessageFormats_proto_msgTypes,
	}.Build()
	File_SystemMessageFormats_proto = out.File
	file_SystemMessageFormats_proto_goTypes = nil
	file_SystemMessageFormats_proto_depIdxs = nil
}
