// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        (unknown)
// source: SystemMessageFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemMessage_Type int32

const (
	SystemMessage_CREATE                  SystemMessage_Type = 0
	SystemMessage_RECREATE                SystemMessage_Type = 1
	SystemMessage_SUSPEND                 SystemMessage_Type = 2
	SystemMessage_RESUME                  SystemMessage_Type = 3
	SystemMessage_TERMINATE               SystemMessage_Type = 4
	SystemMessage_SUPERVISE               SystemMessage_Type = 5
	SystemMessage_WATCH                   SystemMessage_Type = 6
	SystemMessage_UNWATCH                 SystemMessage_Type = 7
	SystemMessage_FAILED                  SystemMessage_Type = 8
	SystemMessage_DEATHWATCH_NOTIFICATION SystemMessage_Type = 9
)

// Enum value maps for SystemMessage_Type.
var (
	SystemMessage_Type_name = map[int32]string{
		0: "CREATE",
		1: "RECREATE",
		2: "SUSPEND",
		3: "RESUME",
		4: "TERMINATE",
		5: "SUPERVISE",
		6: "WATCH",
		7: "UNWATCH",
		8: "FAILED",
		9: "DEATHWATCH_NOTIFICATION",
	}
	SystemMessage_Type_value = map[string]int32{
		"CREATE":                  0,
		"RECREATE":                1,
		"SUSPEND":                 2,
		"RESUME":                  3,
		"TERMINATE":               4,
		"SUPERVISE":               5,
		"WATCH":                   6,
		"UNWATCH":                 7,
		"FAILED":                  8,
		"DEATHWATCH_NOTIFICATION": 9,
	}
)

func (x SystemMessage_Type) Enum() *SystemMessage_Type {
	p := new(SystemMessage_Type)
	*p = x
	return p
}

func (x SystemMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_SystemMessageFormats_proto_enumTypes[0].Descriptor()
}

func (SystemMessage_Type) Type() protoreflect.EnumType {
	return &file_SystemMessageFormats_proto_enumTypes[0]
}

func (x SystemMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SystemMessage_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SystemMessage_Type(num)
	return nil
}

// Deprecated: Use SystemMessage_Type.Descriptor instead.
func (SystemMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{0, 0}
}

type SystemMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type               *SystemMessage_Type         `protobuf:"varint,1,req,name=type,enum=SystemMessage_Type" json:"type,omitempty"`
	WatchData          *WatchData                  `protobuf:"bytes,2,opt,name=watchData" json:"watchData,omitempty"`
	CauseData          *Payload                    `protobuf:"bytes,3,opt,name=causeData" json:"causeData,omitempty"`
	SuperviseData      *SuperviseData              `protobuf:"bytes,5,opt,name=superviseData" json:"superviseData,omitempty"`
	FailedData         *FailedData                 `protobuf:"bytes,6,opt,name=failedData" json:"failedData,omitempty"`
	DwNotificationData *DeathWatchNotificationData `protobuf:"bytes,7,opt,name=dwNotificationData" json:"dwNotificationData,omitempty"`
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemMessageFormats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMessage) GetType() SystemMessage_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SystemMessage_CREATE
}

func (x *SystemMessage) GetWatchData() *WatchData {
	if x != nil {
		return x.WatchData
	}
	return nil
}

func (x *SystemMessage) GetCauseData() *Payload {
	if x != nil {
		return x.CauseData
	}
	return nil
}

func (x *SystemMessage) GetSuperviseData() *SuperviseData {
	if x != nil {
		return x.SuperviseData
	}
	return nil
}

func (x *SystemMessage) GetFailedData() *FailedData {
	if x != nil {
		return x.FailedData
	}
	return nil
}

func (x *SystemMessage) GetDwNotificationData() *DeathWatchNotificationData {
	if x != nil {
		return x.DwNotificationData
	}
	return nil
}

type WatchData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watchee *ActorRef `protobuf:"bytes,1,req,name=watchee" json:"watchee,omitempty"`
	Watcher *ActorRef `protobuf:"bytes,2,req,name=watcher" json:"watcher,omitempty"`
}

func (x *WatchData) Reset() {
	*x = WatchData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemMessageFormats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchData) ProtoMessage() {}

func (x *WatchData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchData.ProtoReflect.Descriptor instead.
func (*WatchData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{1}
}

func (x *WatchData) GetWatchee() *ActorRef {
	if x != nil {
		return x.Watchee
	}
	return nil
}

func (x *WatchData) GetWatcher() *ActorRef {
	if x != nil {
		return x.Watcher
	}
	return nil
}

type SuperviseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Child *ActorRef `protobuf:"bytes,1,req,name=child" json:"child,omitempty"`
	Async *bool     `protobuf:"varint,2,req,name=async" json:"async,omitempty"`
}

func (x *SuperviseData) Reset() {
	*x = SuperviseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemMessageFormats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperviseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperviseData) ProtoMessage() {}

func (x *SuperviseData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperviseData.ProtoReflect.Descriptor instead.
func (*SuperviseData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{2}
}

func (x *SuperviseData) GetChild() *ActorRef {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *SuperviseData) GetAsync() bool {
	if x != nil && x.Async != nil {
		return *x.Async
	}
	return false
}

type FailedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Child *ActorRef `protobuf:"bytes,1,req,name=child" json:"child,omitempty"`
	Uid   *uint64   `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
}

func (x *FailedData) Reset() {
	*x = FailedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemMessageFormats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedData) ProtoMessage() {}

func (x *FailedData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedData.ProtoReflect.Descriptor instead.
func (*FailedData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{3}
}

func (x *FailedData) GetChild() *ActorRef {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *FailedData) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

type DeathWatchNotificationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor              *ActorRef `protobuf:"bytes,1,req,name=actor" json:"actor,omitempty"`
	ExistenceConfirmed *bool     `protobuf:"varint,2,req,name=existenceConfirmed" json:"existenceConfirmed,omitempty"`
	AddressTerminated  *bool     `protobuf:"varint,3,req,name=addressTerminated" json:"addressTerminated,omitempty"`
}

func (x *DeathWatchNotificationData) Reset() {
	*x = DeathWatchNotificationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemMessageFormats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeathWatchNotificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathWatchNotificationData) ProtoMessage() {}

func (x *DeathWatchNotificationData) ProtoReflect() protoreflect.Message {
	mi := &file_SystemMessageFormats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathWatchNotificationData.ProtoReflect.Descriptor instead.
func (*DeathWatchNotificationData) Descriptor() ([]byte, []int) {
	return file_SystemMessageFormats_proto_rawDescGZIP(), []int{4}
}

func (x *DeathWatchNotificationData) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DeathWatchNotificationData) GetExistenceConfirmed() bool {
	if x != nil && x.ExistenceConfirmed != nil {
		return *x.ExistenceConfirmed
	}
	return false
}

func (x *DeathWatchNotificationData) GetAddressTerminated() bool {
	if x != nil && x.AddressTerminated != nil {
		return *x.AddressTerminated
	}
	return false
}

var File_SystemMessageFormats_proto protoreflect.FileDescriptor

var file_SystemMessageFormats_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x03, 0x0a, 0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x75, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0a,
	0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a,
	0x12, 0x64, 0x77, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x44, 0x65, 0x61, 0x74,
	0x68, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x53,
	0x50, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4d, 0x45,
	0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x10,
	0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x50, 0x45, 0x52, 0x56, 0x49, 0x53, 0x45, 0x10, 0x05,
	0x12, 0x09, 0x0a, 0x05, 0x57, 0x41, 0x54, 0x43, 0x48, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x57, 0x41, 0x54, 0x43, 0x48, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x08, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x41, 0x54, 0x48, 0x57, 0x41, 0x54,
	0x43, 0x48, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x09, 0x22, 0x43, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x07, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x12, 0x1a, 0x0a, 0x07, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x22, 0x38, 0x0a, 0x0d, 0x53, 0x75, 0x70, 0x65, 0x72, 0x76,
	0x69, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x66, 0x12, 0x0d, 0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08,
	0x22, 0x33, 0x0a, 0x0a, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x12, 0x0b, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x04, 0x22, 0x6d, 0x0a, 0x1a, 0x44, 0x65, 0x61, 0x74, 0x68, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x12, 0x1a, 0x0a,
	0x12, 0x65, 0x78, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x12, 0x19, 0x0a, 0x11, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x08, 0x42, 0x0a, 0x48, 0x01, 0x5a, 0x06, 0x2e, 0x2f, 0x61, 0x6b, 0x6b, 0x61,
}

var (
	file_SystemMessageFormats_proto_rawDescOnce sync.Once
	file_SystemMessageFormats_proto_rawDescData = file_SystemMessageFormats_proto_rawDesc
)

func file_SystemMessageFormats_proto_rawDescGZIP() []byte {
	file_SystemMessageFormats_proto_rawDescOnce.Do(func() {
		file_SystemMessageFormats_proto_rawDescData = protoimpl.X.CompressGZIP(file_SystemMessageFormats_proto_rawDescData)
	})
	return file_SystemMessageFormats_proto_rawDescData
}

var file_SystemMessageFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SystemMessageFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_SystemMessageFormats_proto_goTypes = []interface{}{
	(SystemMessage_Type)(0),            // 0: SystemMessage.Type
	(*SystemMessage)(nil),              // 1: SystemMessage
	(*WatchData)(nil),                  // 2: WatchData
	(*SuperviseData)(nil),              // 3: SuperviseData
	(*FailedData)(nil),                 // 4: FailedData
	(*DeathWatchNotificationData)(nil), // 5: DeathWatchNotificationData
	(*Payload)(nil),                    // 6: Payload
	(*ActorRef)(nil),                   // 7: ActorRef
}
var file_SystemMessageFormats_proto_depIdxs = []int32{
	0,  // 0: SystemMessage.type:type_name -> SystemMessage.Type
	2,  // 1: SystemMessage.watchData:type_name -> WatchData
	6,  // 2: SystemMessage.causeData:type_name -> Payload
	3,  // 3: SystemMessage.superviseData:type_name -> SuperviseData
	4,  // 4: SystemMessage.failedData:type_name -> FailedData
	5,  // 5: SystemMessage.dwNotificationData:type_name -> DeathWatchNotificationData
	7,  // 6: WatchData.watchee:type_name -> ActorRef
	7,  // 7: WatchData.watcher:type_name -> ActorRef
	7,  // 8: SuperviseData.child:type_name -> ActorRef
	7,  // 9: FailedData.child:type_name -> ActorRef
	7,  // 10: DeathWatchNotificationData.actor:type_name -> ActorRef
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_SystemMessageFormats_proto_init() }
func file_SystemMessageFormats_proto_init() {
	if File_SystemMessageFormats_proto != nil {
		return
	}
	file_ContainerFormats_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SystemMessageFormats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemMessageFormats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemMessageFormats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuperviseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemMessageFormats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemMessageFormats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeathWatchNotificationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SystemMessageFormats_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SystemMessageFormats_proto_goTypes,
		DependencyIndexes: file_SystemMessageFormats_proto_depIdxs,
		EnumInfos:         file_SystemMessageFormats_proto_enumTypes,
		MessageInfos:      file_SystemMessageFormats_proto_msgTypes,
	}.Build()
	File_SystemMessageFormats_proto = out.File
	file_SystemMessageFormats_proto_rawDesc = nil
	file_SystemMessageFormats_proto_goTypes = nil
	file_SystemMessageFormats_proto_depIdxs = nil
}
