// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        (unknown)
// source: WireFormats.proto

package akka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Defines the type of the AkkaControlMessage command type
type CommandType int32

const (
	CommandType_ASSOCIATE                  CommandType = 1
	CommandType_DISASSOCIATE               CommandType = 2
	CommandType_HEARTBEAT                  CommandType = 3
	CommandType_DISASSOCIATE_SHUTTING_DOWN CommandType = 4 // Remote system is going down and will not accepts new connections
	CommandType_DISASSOCIATE_QUARANTINED   CommandType = 5 // Remote system refused the association since the current system is quarantined
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		1: "ASSOCIATE",
		2: "DISASSOCIATE",
		3: "HEARTBEAT",
		4: "DISASSOCIATE_SHUTTING_DOWN",
		5: "DISASSOCIATE_QUARANTINED",
	}
	CommandType_value = map[string]int32{
		"ASSOCIATE":                  1,
		"DISASSOCIATE":               2,
		"HEARTBEAT":                  3,
		"DISASSOCIATE_SHUTTING_DOWN": 4,
		"DISASSOCIATE_QUARANTINED":   5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_WireFormats_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_WireFormats_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CommandType(num)
	return nil
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{0}
}

// *
// java.util.concurrent.TimeUnit enum
type TimeUnit int32

const (
	TimeUnit_NANOSECONDS  TimeUnit = 1
	TimeUnit_MICROSECONDS TimeUnit = 2
	TimeUnit_MILLISECONDS TimeUnit = 3
	TimeUnit_SECONDS      TimeUnit = 4
	TimeUnit_MINUTES      TimeUnit = 5
	TimeUnit_HOURS        TimeUnit = 6
	TimeUnit_DAYS         TimeUnit = 7
)

// Enum value maps for TimeUnit.
var (
	TimeUnit_name = map[int32]string{
		1: "NANOSECONDS",
		2: "MICROSECONDS",
		3: "MILLISECONDS",
		4: "SECONDS",
		5: "MINUTES",
		6: "HOURS",
		7: "DAYS",
	}
	TimeUnit_value = map[string]int32{
		"NANOSECONDS":  1,
		"MICROSECONDS": 2,
		"MILLISECONDS": 3,
		"SECONDS":      4,
		"MINUTES":      5,
		"HOURS":        6,
		"DAYS":         7,
	}
)

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}

func (x TimeUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_WireFormats_proto_enumTypes[1].Descriptor()
}

func (TimeUnit) Type() protoreflect.EnumType {
	return &file_WireFormats_proto_enumTypes[1]
}

func (x TimeUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TimeUnit) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TimeUnit(num)
	return nil
}

// Deprecated: Use TimeUnit.Descriptor instead.
func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{1}
}

type AckAndEnvelopeContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack      *AcknowledgementInfo `protobuf:"bytes,1,opt,name=ack" json:"ack,omitempty"`
	Envelope *RemoteEnvelope      `protobuf:"bytes,2,opt,name=envelope" json:"envelope,omitempty"`
}

func (x *AckAndEnvelopeContainer) Reset() {
	*x = AckAndEnvelopeContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckAndEnvelopeContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAndEnvelopeContainer) ProtoMessage() {}

func (x *AckAndEnvelopeContainer) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAndEnvelopeContainer.ProtoReflect.Descriptor instead.
func (*AckAndEnvelopeContainer) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{0}
}

func (x *AckAndEnvelopeContainer) GetAck() *AcknowledgementInfo {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *AckAndEnvelopeContainer) GetEnvelope() *RemoteEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// *
// Defines a remote message.
type RemoteEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient *ActorRefData      `protobuf:"bytes,1,req,name=recipient" json:"recipient,omitempty"`
	Message   *SerializedMessage `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Sender    *ActorRefData      `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	Seq       *uint64            `protobuf:"fixed64,5,opt,name=seq" json:"seq,omitempty"`
}

func (x *RemoteEnvelope) Reset() {
	*x = RemoteEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEnvelope) ProtoMessage() {}

func (x *RemoteEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEnvelope.ProtoReflect.Descriptor instead.
func (*RemoteEnvelope) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteEnvelope) GetRecipient() *ActorRefData {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *RemoteEnvelope) GetMessage() *SerializedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RemoteEnvelope) GetSender() *ActorRefData {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RemoteEnvelope) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

type AcknowledgementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CumulativeAck *uint64  `protobuf:"fixed64,1,req,name=cumulativeAck" json:"cumulativeAck,omitempty"`
	Nacks         []uint64 `protobuf:"fixed64,2,rep,name=nacks" json:"nacks,omitempty"`
}

func (x *AcknowledgementInfo) Reset() {
	*x = AcknowledgementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcknowledgementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgementInfo) ProtoMessage() {}

func (x *AcknowledgementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgementInfo.ProtoReflect.Descriptor instead.
func (*AcknowledgementInfo) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{2}
}

func (x *AcknowledgementInfo) GetCumulativeAck() uint64 {
	if x != nil && x.CumulativeAck != nil {
		return *x.CumulativeAck
	}
	return 0
}

func (x *AcknowledgementInfo) GetNacks() []uint64 {
	if x != nil {
		return x.Nacks
	}
	return nil
}

// *
// Defines a remote ActorRef that "remembers" and uses its original Actor instance
// on the original node.
type ActorRefData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
}

func (x *ActorRefData) Reset() {
	*x = ActorRefData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorRefData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRefData) ProtoMessage() {}

func (x *ActorRefData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRefData.ProtoReflect.Descriptor instead.
func (*ActorRefData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{3}
}

func (x *ActorRefData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

// *
// Defines a message.
type SerializedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message         []byte `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	SerializerId    *int32 `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	MessageManifest []byte `protobuf:"bytes,3,opt,name=messageManifest" json:"messageManifest,omitempty"`
}

func (x *SerializedMessage) Reset() {
	*x = SerializedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerializedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedMessage) ProtoMessage() {}

func (x *SerializedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedMessage.ProtoReflect.Descriptor instead.
func (*SerializedMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{4}
}

func (x *SerializedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SerializedMessage) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *SerializedMessage) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

// *
// Defines akka.remote.DaemonMsgCreate
type DaemonMsgCreateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props      *PropsData    `protobuf:"bytes,1,req,name=props" json:"props,omitempty"`
	Deploy     *DeployData   `protobuf:"bytes,2,req,name=deploy" json:"deploy,omitempty"`
	Path       *string       `protobuf:"bytes,3,req,name=path" json:"path,omitempty"`
	Supervisor *ActorRefData `protobuf:"bytes,4,req,name=supervisor" json:"supervisor,omitempty"`
}

func (x *DaemonMsgCreateData) Reset() {
	*x = DaemonMsgCreateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonMsgCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMsgCreateData) ProtoMessage() {}

func (x *DaemonMsgCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMsgCreateData.ProtoReflect.Descriptor instead.
func (*DaemonMsgCreateData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonMsgCreateData) GetProps() *PropsData {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *DaemonMsgCreateData) GetDeploy() *DeployData {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *DaemonMsgCreateData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *DaemonMsgCreateData) GetSupervisor() *ActorRefData {
	if x != nil {
		return x.Supervisor
	}
	return nil
}

// *
// Serialization of akka.actor.Props
type PropsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deploy *DeployData `protobuf:"bytes,2,req,name=deploy" json:"deploy,omitempty"`
	Clazz  *string     `protobuf:"bytes,3,req,name=clazz" json:"clazz,omitempty"`
	Args   [][]byte    `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	// serialized props parameters
	// older wire protocol: contains class name for each arg
	// newer wire protocol: contains string manifest for each arg
	Manifests []string `protobuf:"bytes,5,rep,name=manifests" json:"manifests,omitempty"`
	// newer wire protocol: serializer id for each arg
	SerializerIds []int32 `protobuf:"varint,6,rep,name=serializerIds" json:"serializerIds,omitempty"`
	// additionally a flag per position to indicate if it was
	// serialized with manifest or not
	HasManifest []bool `protobuf:"varint,7,rep,name=hasManifest" json:"hasManifest,omitempty"`
}

func (x *PropsData) Reset() {
	*x = PropsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropsData) ProtoMessage() {}

func (x *PropsData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropsData.ProtoReflect.Descriptor instead.
func (*PropsData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{6}
}

func (x *PropsData) GetDeploy() *DeployData {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *PropsData) GetClazz() string {
	if x != nil && x.Clazz != nil {
		return *x.Clazz
	}
	return ""
}

func (x *PropsData) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PropsData) GetManifests() []string {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *PropsData) GetSerializerIds() []int32 {
	if x != nil {
		return x.SerializerIds
	}
	return nil
}

func (x *PropsData) GetHasManifest() []bool {
	if x != nil {
		return x.HasManifest
	}
	return nil
}

// *
// Serialization of akka.actor.Deploy
type DeployData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path         *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Config       []byte  `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	RouterConfig []byte  `protobuf:"bytes,3,opt,name=routerConfig" json:"routerConfig,omitempty"`
	Scope        []byte  `protobuf:"bytes,4,opt,name=scope" json:"scope,omitempty"`
	Dispatcher   *string `protobuf:"bytes,5,opt,name=dispatcher" json:"dispatcher,omitempty"`
	// older wire protocol: hardcoded class used to look up serializer
	// newer wire protocol: serializer id and manifest available for each
	ScopeSerializerId        *int32  `protobuf:"varint,6,opt,name=scopeSerializerId" json:"scopeSerializerId,omitempty"`
	ScopeManifest            *string `protobuf:"bytes,7,opt,name=scopeManifest" json:"scopeManifest,omitempty"`
	ConfigSerializerId       *int32  `protobuf:"varint,8,opt,name=configSerializerId" json:"configSerializerId,omitempty"`
	ConfigManifest           *string `protobuf:"bytes,9,opt,name=configManifest" json:"configManifest,omitempty"`
	RouterConfigSerializerId *int32  `protobuf:"varint,10,opt,name=routerConfigSerializerId" json:"routerConfigSerializerId,omitempty"`
	RouterConfigManifest     *string `protobuf:"bytes,11,opt,name=routerConfigManifest" json:"routerConfigManifest,omitempty"`
}

func (x *DeployData) Reset() {
	*x = DeployData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployData) ProtoMessage() {}

func (x *DeployData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployData.ProtoReflect.Descriptor instead.
func (*DeployData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{7}
}

func (x *DeployData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *DeployData) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeployData) GetRouterConfig() []byte {
	if x != nil {
		return x.RouterConfig
	}
	return nil
}

func (x *DeployData) GetScope() []byte {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DeployData) GetDispatcher() string {
	if x != nil && x.Dispatcher != nil {
		return *x.Dispatcher
	}
	return ""
}

func (x *DeployData) GetScopeSerializerId() int32 {
	if x != nil && x.ScopeSerializerId != nil {
		return *x.ScopeSerializerId
	}
	return 0
}

func (x *DeployData) GetScopeManifest() string {
	if x != nil && x.ScopeManifest != nil {
		return *x.ScopeManifest
	}
	return ""
}

func (x *DeployData) GetConfigSerializerId() int32 {
	if x != nil && x.ConfigSerializerId != nil {
		return *x.ConfigSerializerId
	}
	return 0
}

func (x *DeployData) GetConfigManifest() string {
	if x != nil && x.ConfigManifest != nil {
		return *x.ConfigManifest
	}
	return ""
}

func (x *DeployData) GetRouterConfigSerializerId() int32 {
	if x != nil && x.RouterConfigSerializerId != nil {
		return *x.RouterConfigSerializerId
	}
	return 0
}

func (x *DeployData) GetRouterConfigManifest() string {
	if x != nil && x.RouterConfigManifest != nil {
		return *x.RouterConfigManifest
	}
	return ""
}

// *
// Message format of Akka Protocol.
// Message contains either a payload or an instruction.
type AkkaProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload     []byte              `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Instruction *AkkaControlMessage `protobuf:"bytes,2,opt,name=instruction" json:"instruction,omitempty"`
}

func (x *AkkaProtocolMessage) Reset() {
	*x = AkkaProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkkaProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkkaProtocolMessage) ProtoMessage() {}

func (x *AkkaProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkkaProtocolMessage.ProtoReflect.Descriptor instead.
func (*AkkaProtocolMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{8}
}

func (x *AkkaProtocolMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AkkaProtocolMessage) GetInstruction() *AkkaControlMessage {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// *
// Defines some control messages for the remoting
type AkkaControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandType   *CommandType       `protobuf:"varint,1,req,name=commandType,enum=CommandType" json:"commandType,omitempty"`
	HandshakeInfo *AkkaHandshakeInfo `protobuf:"bytes,2,opt,name=handshakeInfo" json:"handshakeInfo,omitempty"`
}

func (x *AkkaControlMessage) Reset() {
	*x = AkkaControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkkaControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkkaControlMessage) ProtoMessage() {}

func (x *AkkaControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkkaControlMessage.ProtoReflect.Descriptor instead.
func (*AkkaControlMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{9}
}

func (x *AkkaControlMessage) GetCommandType() CommandType {
	if x != nil && x.CommandType != nil {
		return *x.CommandType
	}
	return CommandType_ASSOCIATE
}

func (x *AkkaControlMessage) GetHandshakeInfo() *AkkaHandshakeInfo {
	if x != nil {
		return x.HandshakeInfo
	}
	return nil
}

type AkkaHandshakeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin *AddressData `protobuf:"bytes,1,req,name=origin" json:"origin,omitempty"`
	Uid    *uint64      `protobuf:"fixed64,2,req,name=uid" json:"uid,omitempty"`
	Cookie *string      `protobuf:"bytes,3,opt,name=cookie" json:"cookie,omitempty"`
}

func (x *AkkaHandshakeInfo) Reset() {
	*x = AkkaHandshakeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkkaHandshakeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkkaHandshakeInfo) ProtoMessage() {}

func (x *AkkaHandshakeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkkaHandshakeInfo.ProtoReflect.Descriptor instead.
func (*AkkaHandshakeInfo) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{10}
}

func (x *AkkaHandshakeInfo) GetOrigin() *AddressData {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *AkkaHandshakeInfo) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *AkkaHandshakeInfo) GetCookie() string {
	if x != nil && x.Cookie != nil {
		return *x.Cookie
	}
	return ""
}

type FiniteDuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int64    `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unit  *TimeUnit `protobuf:"varint,2,req,name=unit,enum=TimeUnit" json:"unit,omitempty"`
}

func (x *FiniteDuration) Reset() {
	*x = FiniteDuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiniteDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiniteDuration) ProtoMessage() {}

func (x *FiniteDuration) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiniteDuration.ProtoReflect.Descriptor instead.
func (*FiniteDuration) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{11}
}

func (x *FiniteDuration) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *FiniteDuration) GetUnit() TimeUnit {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return TimeUnit_NANOSECONDS
}

type RemoteScope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *AddressData `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
}

func (x *RemoteScope) Reset() {
	*x = RemoteScope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteScope) ProtoMessage() {}

func (x *RemoteScope) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteScope.ProtoReflect.Descriptor instead.
func (*RemoteScope) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteScope) GetNode() *AddressData {
	if x != nil {
		return x.Node
	}
	return nil
}

type DefaultResizer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowerBound        *uint32  `protobuf:"varint,1,req,name=lowerBound" json:"lowerBound,omitempty"`
	UpperBound        *uint32  `protobuf:"varint,2,req,name=upperBound" json:"upperBound,omitempty"`
	PressureThreshold *uint32  `protobuf:"varint,3,req,name=pressureThreshold" json:"pressureThreshold,omitempty"`
	RampupRate        *float64 `protobuf:"fixed64,4,req,name=rampupRate" json:"rampupRate,omitempty"`
	BackoffThreshold  *float64 `protobuf:"fixed64,5,req,name=backoffThreshold" json:"backoffThreshold,omitempty"`
	BackoffRate       *float64 `protobuf:"fixed64,6,req,name=backoffRate" json:"backoffRate,omitempty"`
	MessagesPerResize *uint32  `protobuf:"varint,7,req,name=messagesPerResize" json:"messagesPerResize,omitempty"`
}

func (x *DefaultResizer) Reset() {
	*x = DefaultResizer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResizer) ProtoMessage() {}

func (x *DefaultResizer) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResizer.ProtoReflect.Descriptor instead.
func (*DefaultResizer) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{13}
}

func (x *DefaultResizer) GetLowerBound() uint32 {
	if x != nil && x.LowerBound != nil {
		return *x.LowerBound
	}
	return 0
}

func (x *DefaultResizer) GetUpperBound() uint32 {
	if x != nil && x.UpperBound != nil {
		return *x.UpperBound
	}
	return 0
}

func (x *DefaultResizer) GetPressureThreshold() uint32 {
	if x != nil && x.PressureThreshold != nil {
		return *x.PressureThreshold
	}
	return 0
}

func (x *DefaultResizer) GetRampupRate() float64 {
	if x != nil && x.RampupRate != nil {
		return *x.RampupRate
	}
	return 0
}

func (x *DefaultResizer) GetBackoffThreshold() float64 {
	if x != nil && x.BackoffThreshold != nil {
		return *x.BackoffThreshold
	}
	return 0
}

func (x *DefaultResizer) GetBackoffRate() float64 {
	if x != nil && x.BackoffRate != nil {
		return *x.BackoffRate
	}
	return 0
}

func (x *DefaultResizer) GetMessagesPerResize() uint32 {
	if x != nil && x.MessagesPerResize != nil {
		return *x.MessagesPerResize
	}
	return 0
}

type FromConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resizer          *Payload `protobuf:"bytes,1,opt,name=resizer" json:"resizer,omitempty"`
	RouterDispatcher *string  `protobuf:"bytes,2,opt,name=routerDispatcher" json:"routerDispatcher,omitempty"`
}

func (x *FromConfig) Reset() {
	*x = FromConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromConfig) ProtoMessage() {}

func (x *FromConfig) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromConfig.ProtoReflect.Descriptor instead.
func (*FromConfig) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{14}
}

func (x *FromConfig) GetResizer() *Payload {
	if x != nil {
		return x.Resizer
	}
	return nil
}

func (x *FromConfig) GetRouterDispatcher() string {
	if x != nil && x.RouterDispatcher != nil {
		return *x.RouterDispatcher
	}
	return ""
}

type GenericRoutingPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NrOfInstances     *uint32  `protobuf:"varint,1,req,name=nrOfInstances" json:"nrOfInstances,omitempty"`
	RouterDispatcher  *string  `protobuf:"bytes,2,opt,name=routerDispatcher" json:"routerDispatcher,omitempty"`
	UsePoolDispatcher *bool    `protobuf:"varint,3,req,name=usePoolDispatcher" json:"usePoolDispatcher,omitempty"`
	Resizer           *Payload `protobuf:"bytes,4,opt,name=resizer" json:"resizer,omitempty"`
}

func (x *GenericRoutingPool) Reset() {
	*x = GenericRoutingPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericRoutingPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRoutingPool) ProtoMessage() {}

func (x *GenericRoutingPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRoutingPool.ProtoReflect.Descriptor instead.
func (*GenericRoutingPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{15}
}

func (x *GenericRoutingPool) GetNrOfInstances() uint32 {
	if x != nil && x.NrOfInstances != nil {
		return *x.NrOfInstances
	}
	return 0
}

func (x *GenericRoutingPool) GetRouterDispatcher() string {
	if x != nil && x.RouterDispatcher != nil {
		return *x.RouterDispatcher
	}
	return ""
}

func (x *GenericRoutingPool) GetUsePoolDispatcher() bool {
	if x != nil && x.UsePoolDispatcher != nil {
		return *x.UsePoolDispatcher
	}
	return false
}

func (x *GenericRoutingPool) GetResizer() *Payload {
	if x != nil {
		return x.Resizer
	}
	return nil
}

type ScatterGatherPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generic *GenericRoutingPool `protobuf:"bytes,1,req,name=generic" json:"generic,omitempty"`
	Within  *FiniteDuration     `protobuf:"bytes,2,req,name=within" json:"within,omitempty"`
}

func (x *ScatterGatherPool) Reset() {
	*x = ScatterGatherPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScatterGatherPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScatterGatherPool) ProtoMessage() {}

func (x *ScatterGatherPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScatterGatherPool.ProtoReflect.Descriptor instead.
func (*ScatterGatherPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{16}
}

func (x *ScatterGatherPool) GetGeneric() *GenericRoutingPool {
	if x != nil {
		return x.Generic
	}
	return nil
}

func (x *ScatterGatherPool) GetWithin() *FiniteDuration {
	if x != nil {
		return x.Within
	}
	return nil
}

type TailChoppingPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generic  *GenericRoutingPool `protobuf:"bytes,1,req,name=generic" json:"generic,omitempty"`
	Within   *FiniteDuration     `protobuf:"bytes,2,req,name=within" json:"within,omitempty"`
	Interval *FiniteDuration     `protobuf:"bytes,3,req,name=interval" json:"interval,omitempty"`
}

func (x *TailChoppingPool) Reset() {
	*x = TailChoppingPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TailChoppingPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailChoppingPool) ProtoMessage() {}

func (x *TailChoppingPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailChoppingPool.ProtoReflect.Descriptor instead.
func (*TailChoppingPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{17}
}

func (x *TailChoppingPool) GetGeneric() *GenericRoutingPool {
	if x != nil {
		return x.Generic
	}
	return nil
}

func (x *TailChoppingPool) GetWithin() *FiniteDuration {
	if x != nil {
		return x.Within
	}
	return nil
}

func (x *TailChoppingPool) GetInterval() *FiniteDuration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// *
// Defines a remote address.
type AddressData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	System   *string `protobuf:"bytes,1,req,name=system" json:"system,omitempty"`
	Hostname *string `protobuf:"bytes,2,req,name=hostname" json:"hostname,omitempty"`
	Port     *uint32 `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	Protocol *string `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
}

func (x *AddressData) Reset() {
	*x = AddressData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressData) ProtoMessage() {}

func (x *AddressData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressData.ProtoReflect.Descriptor instead.
func (*AddressData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{18}
}

func (x *AddressData) GetSystem() string {
	if x != nil && x.System != nil {
		return *x.System
	}
	return ""
}

func (x *AddressData) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *AddressData) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *AddressData) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

type RemoteRouterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Local *Payload       `protobuf:"bytes,1,req,name=local" json:"local,omitempty"`
	Nodes []*AddressData `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (x *RemoteRouterConfig) Reset() {
	*x = RemoteRouterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WireFormats_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteRouterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRouterConfig) ProtoMessage() {}

func (x *RemoteRouterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRouterConfig.ProtoReflect.Descriptor instead.
func (*RemoteRouterConfig) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{19}
}

func (x *RemoteRouterConfig) GetLocal() *Payload {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *RemoteRouterConfig) GetNodes() []*AddressData {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_WireFormats_proto protoreflect.FileDescriptor

var file_WireFormats_proto_rawDesc = []byte{
	0x0a, 0x11, 0x57, 0x69, 0x72, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x17, 0x41,
	0x63, 0x6b, 0x41, 0x6e, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x08, 0x65, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x22, 0x83, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x23, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0b, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x06, 0x22, 0x3b, 0x0a, 0x13, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x0d, 0x63, 0x75, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x41, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x06,
	0x12, 0x0d, 0x0a, 0x05, 0x6e, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x06, 0x22,
	0x1c, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0c, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x22, 0x53, 0x0a,
	0x11, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0c, 0x12, 0x14, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x12, 0x17, 0x0a, 0x0f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x22, 0x7e, 0x0a, 0x13, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0c, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x12,
	0x21, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0d, 0x0a,
	0x05, 0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x12, 0x0c, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x12, 0x11, 0x0a, 0x09, 0x6d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x12, 0x15, 0x0a,
	0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x05, 0x12, 0x13, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x4d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x08, 0x22, 0x89, 0x02, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x12, 0x0e, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x14, 0x0a, 0x0c, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x0d, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x12, 0x0a, 0x0a, 0x64,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x12,
	0x19, 0x0a, 0x11, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x12, 0x15, 0x0a, 0x0d, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x1a, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x12, 0x16, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x12, 0x20, 0x0a, 0x18, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x12, 0x1c, 0x0a, 0x14, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x22, 0x50, 0x0a, 0x13, 0x41, 0x6b, 0x6b, 0x61, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x28, 0x0a,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x6b, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x12, 0x41, 0x6b, 0x6b, 0x61, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x29, 0x0a, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x6b, 0x6b, 0x61, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4e, 0x0a, 0x11, 0x41,
	0x6b, 0x6b, 0x61, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0b,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x06, 0x12, 0x0e, 0x0a, 0x06, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x22, 0x38, 0x0a, 0x0e, 0x46,
	0x69, 0x6e, 0x69, 0x74, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x12, 0x17, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x22, 0xb1, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x0a, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x12, 0x12, 0x0a, 0x0a, 0x75, 0x70, 0x70, 0x65, 0x72,
	0x42, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x12, 0x19, 0x0a, 0x11, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x12, 0x12, 0x0a, 0x0a, 0x72, 0x61, 0x6d, 0x70, 0x75, 0x70,
	0x52, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x01, 0x12, 0x18, 0x0a, 0x10, 0x62, 0x61,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x05,
	0x20, 0x02, 0x28, 0x01, 0x12, 0x13, 0x0a, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x02, 0x28, 0x01, 0x12, 0x19, 0x0a, 0x11, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x50, 0x65, 0x72, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x0d, 0x22, 0x41, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a,
	0x10, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x22, 0x7b, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x15, 0x0a,
	0x0d, 0x6e, 0x72, 0x4f, 0x66, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0d, 0x12, 0x18, 0x0a, 0x10, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x12, 0x19,
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x72, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5a, 0x0a, 0x11, 0x53, 0x63, 0x61, 0x74, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x07, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x12,
	0x1f, 0x0a, 0x06, 0x77, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x7c, 0x0a, 0x10, 0x54, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1f, 0x0a, 0x06, 0x77, 0x69,
	0x74, 0x68, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x74, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x46, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f,
	0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x12, 0x10, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x12,
	0x0c, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x12, 0x10, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x22,
	0x4a, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b,
	0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x7b, 0x0a, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x53,
	0x53, 0x4f, 0x43, 0x49, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53,
	0x41, 0x53, 0x53, 0x4f, 0x43, 0x49, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x49,
	0x53, 0x41, 0x53, 0x53, 0x4f, 0x43, 0x49, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x54,
	0x49, 0x4e, 0x47, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x49,
	0x53, 0x41, 0x53, 0x53, 0x4f, 0x43, 0x49, 0x41, 0x54, 0x45, 0x5f, 0x51, 0x55, 0x41, 0x52, 0x41,
	0x4e, 0x54, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x05, 0x2a, 0x6e, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x41, 0x4e, 0x4f, 0x53, 0x45, 0x43, 0x4f,
	0x4e, 0x44, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49, 0x43, 0x52, 0x4f, 0x53, 0x45,
	0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49, 0x4c, 0x4c, 0x49,
	0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x43,
	0x4f, 0x4e, 0x44, 0x53, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45,
	0x53, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x06, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x41, 0x59, 0x53, 0x10, 0x07, 0x42, 0x0a, 0x48, 0x01, 0x5a, 0x06, 0x2e, 0x2f,
	0x61, 0x6b, 0x6b, 0x61,
}

var (
	file_WireFormats_proto_rawDescOnce sync.Once
	file_WireFormats_proto_rawDescData = file_WireFormats_proto_rawDesc
)

func file_WireFormats_proto_rawDescGZIP() []byte {
	file_WireFormats_proto_rawDescOnce.Do(func() {
		file_WireFormats_proto_rawDescData = protoimpl.X.CompressGZIP(file_WireFormats_proto_rawDescData)
	})
	return file_WireFormats_proto_rawDescData
}

var file_WireFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_WireFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_WireFormats_proto_goTypes = []interface{}{
	(CommandType)(0),                // 0: CommandType
	(TimeUnit)(0),                   // 1: TimeUnit
	(*AckAndEnvelopeContainer)(nil), // 2: AckAndEnvelopeContainer
	(*RemoteEnvelope)(nil),          // 3: RemoteEnvelope
	(*AcknowledgementInfo)(nil),     // 4: AcknowledgementInfo
	(*ActorRefData)(nil),            // 5: ActorRefData
	(*SerializedMessage)(nil),       // 6: SerializedMessage
	(*DaemonMsgCreateData)(nil),     // 7: DaemonMsgCreateData
	(*PropsData)(nil),               // 8: PropsData
	(*DeployData)(nil),              // 9: DeployData
	(*AkkaProtocolMessage)(nil),     // 10: AkkaProtocolMessage
	(*AkkaControlMessage)(nil),      // 11: AkkaControlMessage
	(*AkkaHandshakeInfo)(nil),       // 12: AkkaHandshakeInfo
	(*FiniteDuration)(nil),          // 13: FiniteDuration
	(*RemoteScope)(nil),             // 14: RemoteScope
	(*DefaultResizer)(nil),          // 15: DefaultResizer
	(*FromConfig)(nil),              // 16: FromConfig
	(*GenericRoutingPool)(nil),      // 17: GenericRoutingPool
	(*ScatterGatherPool)(nil),       // 18: ScatterGatherPool
	(*TailChoppingPool)(nil),        // 19: TailChoppingPool
	(*AddressData)(nil),             // 20: AddressData
	(*RemoteRouterConfig)(nil),      // 21: RemoteRouterConfig
	(*Payload)(nil),                 // 22: Payload
}
var file_WireFormats_proto_depIdxs = []int32{
	4,  // 0: AckAndEnvelopeContainer.ack:type_name -> AcknowledgementInfo
	3,  // 1: AckAndEnvelopeContainer.envelope:type_name -> RemoteEnvelope
	5,  // 2: RemoteEnvelope.recipient:type_name -> ActorRefData
	6,  // 3: RemoteEnvelope.message:type_name -> SerializedMessage
	5,  // 4: RemoteEnvelope.sender:type_name -> ActorRefData
	8,  // 5: DaemonMsgCreateData.props:type_name -> PropsData
	9,  // 6: DaemonMsgCreateData.deploy:type_name -> DeployData
	5,  // 7: DaemonMsgCreateData.supervisor:type_name -> ActorRefData
	9,  // 8: PropsData.deploy:type_name -> DeployData
	11, // 9: AkkaProtocolMessage.instruction:type_name -> AkkaControlMessage
	0,  // 10: AkkaControlMessage.commandType:type_name -> CommandType
	12, // 11: AkkaControlMessage.handshakeInfo:type_name -> AkkaHandshakeInfo
	20, // 12: AkkaHandshakeInfo.origin:type_name -> AddressData
	1,  // 13: FiniteDuration.unit:type_name -> TimeUnit
	20, // 14: RemoteScope.node:type_name -> AddressData
	22, // 15: FromConfig.resizer:type_name -> Payload
	22, // 16: GenericRoutingPool.resizer:type_name -> Payload
	17, // 17: ScatterGatherPool.generic:type_name -> GenericRoutingPool
	13, // 18: ScatterGatherPool.within:type_name -> FiniteDuration
	17, // 19: TailChoppingPool.generic:type_name -> GenericRoutingPool
	13, // 20: TailChoppingPool.within:type_name -> FiniteDuration
	13, // 21: TailChoppingPool.interval:type_name -> FiniteDuration
	22, // 22: RemoteRouterConfig.local:type_name -> Payload
	20, // 23: RemoteRouterConfig.nodes:type_name -> AddressData
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_WireFormats_proto_init() }
func file_WireFormats_proto_init() {
	if File_WireFormats_proto != nil {
		return
	}
	file_ContainerFormats_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_WireFormats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckAndEnvelopeContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcknowledgementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorRefData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerializedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonMsgCreateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AkkaProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AkkaControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AkkaHandshakeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiniteDuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteScope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResizer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericRoutingPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScatterGatherPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TailChoppingPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WireFormats_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteRouterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WireFormats_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WireFormats_proto_goTypes,
		DependencyIndexes: file_WireFormats_proto_depIdxs,
		EnumInfos:         file_WireFormats_proto_enumTypes,
		MessageInfos:      file_WireFormats_proto_msgTypes,
	}.Build()
	File_WireFormats_proto = out.File
	file_WireFormats_proto_rawDesc = nil
	file_WireFormats_proto_goTypes = nil
	file_WireFormats_proto_depIdxs = nil
}
