// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common.proto

package schedulerx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpstreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       *string                `protobuf:"bytes,1,req,name=job_name,json=jobName" json:"job_name,omitempty"`
	Data          *string                `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamData) Reset() {
	*x = UpstreamData{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamData) ProtoMessage() {}

func (x *UpstreamData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamData.ProtoReflect.Descriptor instead.
func (*UpstreamData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamData) GetJobName() string {
	if x != nil && x.JobName != nil {
		return *x.JobName
	}
	return ""
}

func (x *UpstreamData) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type LabelWorkerAddrsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *string                `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	WorkerAddrs   []string               `protobuf:"bytes,2,rep,name=workerAddrs" json:"workerAddrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelWorkerAddrsEntry) Reset() {
	*x = LabelWorkerAddrsEntry{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelWorkerAddrsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelWorkerAddrsEntry) ProtoMessage() {}

func (x *LabelWorkerAddrsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelWorkerAddrsEntry.ProtoReflect.Descriptor instead.
func (*LabelWorkerAddrsEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *LabelWorkerAddrsEntry) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *LabelWorkerAddrsEntry) GetWorkerAddrs() []string {
	if x != nil {
		return x.WorkerAddrs
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12 schedulerx_worker.internal.proto\"=\n" +
	"\fUpstreamData\x12\x19\n" +
	"\bjob_name\x18\x01 \x02(\tR\ajobName\x12\x12\n" +
	"\x04data\x18\x02 \x02(\tR\x04data\"O\n" +
	"\x15LabelWorkerAddrsEntry\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vworkerAddrs\x18\x02 \x03(\tR\vworkerAddrsB\x0eZ\f./schedulerx"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(*UpstreamData)(nil),          // 0: schedulerx_worker.internal.proto.UpstreamData
	(*LabelWorkerAddrsEntry)(nil), // 1: schedulerx_worker.internal.proto.LabelWorkerAddrsEntry
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
