// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: server.proto

package schedulerx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server submit job instance to Worker
type ServerSubmitJobInstanceRequest struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	JobId                *int64                   `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId        *int64                   `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	ScheduleTime         *int64                   `protobuf:"varint,3,req,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	DataTime             *int64                   `protobuf:"varint,4,req,name=data_time,json=dataTime" json:"data_time,omitempty"`
	JobType              *string                  `protobuf:"bytes,5,req,name=job_type,json=jobType" json:"job_type,omitempty"`
	ExecuteMode          *string                  `protobuf:"bytes,6,req,name=execute_mode,json=executeMode" json:"execute_mode,omitempty"`
	Content              *string                  `protobuf:"bytes,7,req,name=content" json:"content,omitempty"`
	User                 *string                  `protobuf:"bytes,8,req,name=user" json:"user,omitempty"`
	Xattrs               *string                  `protobuf:"bytes,9,opt,name=xattrs" json:"xattrs,omitempty"`
	Parameters           *string                  `protobuf:"bytes,10,opt,name=parameters" json:"parameters,omitempty"`
	Workers              []string                 `protobuf:"bytes,11,rep,name=workers" json:"workers,omitempty"`
	JobConcurrency       *int32                   `protobuf:"varint,12,req,name=job_concurrency,json=jobConcurrency" json:"job_concurrency,omitempty"`
	RegionId             *int32                   `protobuf:"varint,13,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	AppGroupId           *int64                   `protobuf:"varint,14,req,name=app_group_id,json=appGroupId" json:"app_group_id,omitempty"`
	InstanceParameters   *string                  `protobuf:"bytes,15,opt,name=instance_parameters,json=instanceParameters" json:"instance_parameters,omitempty"`
	UpstreamData         []*UpstreamData          `protobuf:"bytes,16,rep,name=upstreamData" json:"upstreamData,omitempty"`
	GroupId              *string                  `protobuf:"bytes,17,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	TimeType             *int32                   `protobuf:"varint,18,opt,name=time_type,json=timeType" json:"time_type,omitempty"`
	TimeExpression       *string                  `protobuf:"bytes,19,opt,name=time_expression,json=timeExpression" json:"time_expression,omitempty"`
	MaxAttempt           *int32                   `protobuf:"varint,20,opt,name=max_attempt,json=maxAttempt" json:"max_attempt,omitempty"`
	Attempt              *int32                   `protobuf:"varint,21,opt,name=attempt" json:"attempt,omitempty"`
	WfInstanceId         *int64                   `protobuf:"varint,22,opt,name=wf_instance_id,json=wfInstanceId" json:"wf_instance_id,omitempty"`
	JobName              *string                  `protobuf:"bytes,23,opt,name=job_name,json=jobName" json:"job_name,omitempty"`
	Namespace            *string                  `protobuf:"bytes,24,opt,name=namespace" json:"namespace,omitempty"`
	TriggerType          *int32                   `protobuf:"varint,25,opt,name=trigger_type,json=triggerType" json:"trigger_type,omitempty"`
	RouteStrategyType    *int32                   `protobuf:"varint,26,opt,name=route_strategy_type,json=routeStrategyType" json:"route_strategy_type,omitempty"`
	RouteStrategyContent *string                  `protobuf:"bytes,27,opt,name=route_strategy_content,json=routeStrategyContent" json:"route_strategy_content,omitempty"`
	LabelWorkerAddrsMap  []*LabelWorkerAddrsEntry `protobuf:"bytes,28,rep,name=label_worker_addrs_map,json=labelWorkerAddrsMap" json:"label_worker_addrs_map,omitempty"`
	Template             *string                  `protobuf:"bytes,29,opt,name=template" json:"template,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerSubmitJobInstanceRequest) Reset() {
	*x = ServerSubmitJobInstanceRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSubmitJobInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSubmitJobInstanceRequest) ProtoMessage() {}

func (x *ServerSubmitJobInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSubmitJobInstanceRequest.ProtoReflect.Descriptor instead.
func (*ServerSubmitJobInstanceRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerSubmitJobInstanceRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetScheduleTime() int64 {
	if x != nil && x.ScheduleTime != nil {
		return *x.ScheduleTime
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetDataTime() int64 {
	if x != nil && x.DataTime != nil {
		return *x.DataTime
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetJobType() string {
	if x != nil && x.JobType != nil {
		return *x.JobType
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetExecuteMode() string {
	if x != nil && x.ExecuteMode != nil {
		return *x.ExecuteMode
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetXattrs() string {
	if x != nil && x.Xattrs != nil {
		return *x.Xattrs
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetWorkers() []string {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ServerSubmitJobInstanceRequest) GetJobConcurrency() int32 {
	if x != nil && x.JobConcurrency != nil {
		return *x.JobConcurrency
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetRegionId() int32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetAppGroupId() int64 {
	if x != nil && x.AppGroupId != nil {
		return *x.AppGroupId
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetInstanceParameters() string {
	if x != nil && x.InstanceParameters != nil {
		return *x.InstanceParameters
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetUpstreamData() []*UpstreamData {
	if x != nil {
		return x.UpstreamData
	}
	return nil
}

func (x *ServerSubmitJobInstanceRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetTimeType() int32 {
	if x != nil && x.TimeType != nil {
		return *x.TimeType
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetTimeExpression() string {
	if x != nil && x.TimeExpression != nil {
		return *x.TimeExpression
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetMaxAttempt() int32 {
	if x != nil && x.MaxAttempt != nil {
		return *x.MaxAttempt
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetAttempt() int32 {
	if x != nil && x.Attempt != nil {
		return *x.Attempt
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetWfInstanceId() int64 {
	if x != nil && x.WfInstanceId != nil {
		return *x.WfInstanceId
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetJobName() string {
	if x != nil && x.JobName != nil {
		return *x.JobName
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetTriggerType() int32 {
	if x != nil && x.TriggerType != nil {
		return *x.TriggerType
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetRouteStrategyType() int32 {
	if x != nil && x.RouteStrategyType != nil {
		return *x.RouteStrategyType
	}
	return 0
}

func (x *ServerSubmitJobInstanceRequest) GetRouteStrategyContent() string {
	if x != nil && x.RouteStrategyContent != nil {
		return *x.RouteStrategyContent
	}
	return ""
}

func (x *ServerSubmitJobInstanceRequest) GetLabelWorkerAddrsMap() []*LabelWorkerAddrsEntry {
	if x != nil {
		return x.LabelWorkerAddrsMap
	}
	return nil
}

func (x *ServerSubmitJobInstanceRequest) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

type ServerSubmitJobInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerSubmitJobInstanceResponse fields.
const (
	Default_ServerSubmitJobInstanceResponse_Message = string("")
)

func (x *ServerSubmitJobInstanceResponse) Reset() {
	*x = ServerSubmitJobInstanceResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSubmitJobInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSubmitJobInstanceResponse) ProtoMessage() {}

func (x *ServerSubmitJobInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSubmitJobInstanceResponse.ProtoReflect.Descriptor instead.
func (*ServerSubmitJobInstanceResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerSubmitJobInstanceResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerSubmitJobInstanceResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerSubmitJobInstanceResponse_Message
}

// Server kill job instance to Worker
type ServerKillJobInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	User          *string                `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	DestoryJob    *bool                  `protobuf:"varint,4,opt,name=destory_job,json=destoryJob" json:"destory_job,omitempty"`
	JobType       *string                `protobuf:"bytes,5,opt,name=job_type,json=jobType" json:"job_type,omitempty"`
	Content       *string                `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	Namespace     *string                `protobuf:"bytes,7,opt,name=namespace" json:"namespace,omitempty"`
	Xattrs        *string                `protobuf:"bytes,8,opt,name=xattrs" json:"xattrs,omitempty"`
	ExecuteMode   *string                `protobuf:"bytes,9,opt,name=execute_mode,json=executeMode" json:"execute_mode,omitempty"`
	AppGroupId    *int64                 `protobuf:"varint,10,opt,name=app_group_id,json=appGroupId" json:"app_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerKillJobInstanceRequest) Reset() {
	*x = ServerKillJobInstanceRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKillJobInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKillJobInstanceRequest) ProtoMessage() {}

func (x *ServerKillJobInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKillJobInstanceRequest.ProtoReflect.Descriptor instead.
func (*ServerKillJobInstanceRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerKillJobInstanceRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerKillJobInstanceRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerKillJobInstanceRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetDestoryJob() bool {
	if x != nil && x.DestoryJob != nil {
		return *x.DestoryJob
	}
	return false
}

func (x *ServerKillJobInstanceRequest) GetJobType() string {
	if x != nil && x.JobType != nil {
		return *x.JobType
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetXattrs() string {
	if x != nil && x.Xattrs != nil {
		return *x.Xattrs
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetExecuteMode() string {
	if x != nil && x.ExecuteMode != nil {
		return *x.ExecuteMode
	}
	return ""
}

func (x *ServerKillJobInstanceRequest) GetAppGroupId() int64 {
	if x != nil && x.AppGroupId != nil {
		return *x.AppGroupId
	}
	return 0
}

type ServerKillJobInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerKillJobInstanceResponse fields.
const (
	Default_ServerKillJobInstanceResponse_Message = string("")
)

func (x *ServerKillJobInstanceResponse) Reset() {
	*x = ServerKillJobInstanceResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKillJobInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKillJobInstanceResponse) ProtoMessage() {}

func (x *ServerKillJobInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKillJobInstanceResponse.ProtoReflect.Descriptor instead.
func (*ServerKillJobInstanceResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServerKillJobInstanceResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerKillJobInstanceResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerKillJobInstanceResponse_Message
}

// Server kill task intance to Worker
type ServerKillTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	TaskId        *int64                 `protobuf:"varint,3,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	User          *string                `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	WorkerId      *string                `protobuf:"bytes,5,req,name=worker_id,json=workerId" json:"worker_id,omitempty"`
	WorkerAddr    *string                `protobuf:"bytes,6,req,name=worker_addr,json=workerAddr" json:"worker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerKillTaskRequest) Reset() {
	*x = ServerKillTaskRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKillTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKillTaskRequest) ProtoMessage() {}

func (x *ServerKillTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKillTaskRequest.ProtoReflect.Descriptor instead.
func (*ServerKillTaskRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *ServerKillTaskRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerKillTaskRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerKillTaskRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *ServerKillTaskRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ServerKillTaskRequest) GetWorkerId() string {
	if x != nil && x.WorkerId != nil {
		return *x.WorkerId
	}
	return ""
}

func (x *ServerKillTaskRequest) GetWorkerAddr() string {
	if x != nil && x.WorkerAddr != nil {
		return *x.WorkerAddr
	}
	return ""
}

type ServerKillTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerKillTaskResponse fields.
const (
	Default_ServerKillTaskResponse_Message = string("")
)

func (x *ServerKillTaskResponse) Reset() {
	*x = ServerKillTaskResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKillTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKillTaskResponse) ProtoMessage() {}

func (x *ServerKillTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKillTaskResponse.ProtoReflect.Descriptor instead.
func (*ServerKillTaskResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *ServerKillTaskResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerKillTaskResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerKillTaskResponse_Message
}

// create region
type ServerCreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	User          *string                `protobuf:"bytes,3,req,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCreateRegionRequest) Reset() {
	*x = ServerCreateRegionRequest{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCreateRegionRequest) ProtoMessage() {}

func (x *ServerCreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCreateRegionRequest.ProtoReflect.Descriptor instead.
func (*ServerCreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *ServerCreateRegionRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ServerCreateRegionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ServerCreateRegionRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

type ServerCreateRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerCreateRegionResponse fields.
const (
	Default_ServerCreateRegionResponse_Message = string("")
)

func (x *ServerCreateRegionResponse) Reset() {
	*x = ServerCreateRegionResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCreateRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCreateRegionResponse) ProtoMessage() {}

func (x *ServerCreateRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCreateRegionResponse.ProtoReflect.Descriptor instead.
func (*ServerCreateRegionResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *ServerCreateRegionResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerCreateRegionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerCreateRegionResponse_Message
}

// create app
type ServerCreateAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	RegionId      *int32                 `protobuf:"varint,3,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	Creator       *string                `protobuf:"bytes,4,req,name=creator" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCreateAppRequest) Reset() {
	*x = ServerCreateAppRequest{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCreateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCreateAppRequest) ProtoMessage() {}

func (x *ServerCreateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCreateAppRequest.ProtoReflect.Descriptor instead.
func (*ServerCreateAppRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *ServerCreateAppRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ServerCreateAppRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ServerCreateAppRequest) GetRegionId() int32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *ServerCreateAppRequest) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

type ServerCreateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerCreateAppResponse fields.
const (
	Default_ServerCreateAppResponse_Message = string("")
)

func (x *ServerCreateAppResponse) Reset() {
	*x = ServerCreateAppResponse{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCreateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCreateAppResponse) ProtoMessage() {}

func (x *ServerCreateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCreateAppResponse.ProtoReflect.Descriptor instead.
func (*ServerCreateAppResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *ServerCreateAppResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerCreateAppResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerCreateAppResponse_Message
}

// retry tasks
type RetryTaskEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *int64                 `protobuf:"varint,1,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	TaskName      *string                `protobuf:"bytes,2,req,name=task_name,json=taskName" json:"task_name,omitempty"`
	WorkerAddr    *string                `protobuf:"bytes,3,req,name=worker_addr,json=workerAddr" json:"worker_addr,omitempty"`
	OldStatus     *int32                 `protobuf:"varint,4,req,name=old_status,json=oldStatus" json:"old_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskEntity) Reset() {
	*x = RetryTaskEntity{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskEntity) ProtoMessage() {}

func (x *RetryTaskEntity) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskEntity.ProtoReflect.Descriptor instead.
func (*RetryTaskEntity) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *RetryTaskEntity) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *RetryTaskEntity) GetTaskName() string {
	if x != nil && x.TaskName != nil {
		return *x.TaskName
	}
	return ""
}

func (x *RetryTaskEntity) GetWorkerAddr() string {
	if x != nil && x.WorkerAddr != nil {
		return *x.WorkerAddr
	}
	return ""
}

func (x *RetryTaskEntity) GetOldStatus() int32 {
	if x != nil && x.OldStatus != nil {
		return *x.OldStatus
	}
	return 0
}

type ServerRetryTasksRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId      *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	ScheduleTime       *int64                 `protobuf:"varint,3,req,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	DataTime           *int64                 `protobuf:"varint,4,req,name=data_time,json=dataTime" json:"data_time,omitempty"`
	JobType            *string                `protobuf:"bytes,5,req,name=job_type,json=jobType" json:"job_type,omitempty"`
	ExecuteMode        *string                `protobuf:"bytes,6,req,name=execute_mode,json=executeMode" json:"execute_mode,omitempty"`
	Content            *string                `protobuf:"bytes,7,req,name=content" json:"content,omitempty"`
	User               *string                `protobuf:"bytes,8,req,name=user" json:"user,omitempty"`
	Xattrs             *string                `protobuf:"bytes,9,opt,name=xattrs" json:"xattrs,omitempty"`
	Parameters         *string                `protobuf:"bytes,10,opt,name=parameters" json:"parameters,omitempty"`
	Workers            []string               `protobuf:"bytes,11,rep,name=workers" json:"workers,omitempty"`
	JobConcurrency     *int32                 `protobuf:"varint,12,req,name=job_concurrency,json=jobConcurrency" json:"job_concurrency,omitempty"`
	RegionId           *int32                 `protobuf:"varint,13,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	AppGroupId         *int64                 `protobuf:"varint,14,req,name=app_group_id,json=appGroupId" json:"app_group_id,omitempty"`
	InstanceParameters *string                `protobuf:"bytes,15,opt,name=instance_parameters,json=instanceParameters" json:"instance_parameters,omitempty"`
	UpstreamData       []*UpstreamData        `protobuf:"bytes,16,rep,name=upstreamData" json:"upstreamData,omitempty"`
	GroupId            *string                `protobuf:"bytes,17,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	TimeType           *int32                 `protobuf:"varint,18,opt,name=time_type,json=timeType" json:"time_type,omitempty"`
	TimeExpression     *string                `protobuf:"bytes,19,opt,name=time_expression,json=timeExpression" json:"time_expression,omitempty"`
	MaxAttempt         *int32                 `protobuf:"varint,20,opt,name=max_attempt,json=maxAttempt" json:"max_attempt,omitempty"`
	Attempt            *int32                 `protobuf:"varint,21,opt,name=attempt" json:"attempt,omitempty"`
	WfInstanceId       *int64                 `protobuf:"varint,22,opt,name=wf_instance_id,json=wfInstanceId" json:"wf_instance_id,omitempty"`
	RetryTaskEntity    []*RetryTaskEntity     `protobuf:"bytes,23,rep,name=retry_task_entity,json=retryTaskEntity" json:"retry_task_entity,omitempty"`
	JobName            *string                `protobuf:"bytes,24,opt,name=job_name,json=jobName" json:"job_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerRetryTasksRequest) Reset() {
	*x = ServerRetryTasksRequest{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRetryTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRetryTasksRequest) ProtoMessage() {}

func (x *ServerRetryTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRetryTasksRequest.ProtoReflect.Descriptor instead.
func (*ServerRetryTasksRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *ServerRetryTasksRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetScheduleTime() int64 {
	if x != nil && x.ScheduleTime != nil {
		return *x.ScheduleTime
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetDataTime() int64 {
	if x != nil && x.DataTime != nil {
		return *x.DataTime
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetJobType() string {
	if x != nil && x.JobType != nil {
		return *x.JobType
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetExecuteMode() string {
	if x != nil && x.ExecuteMode != nil {
		return *x.ExecuteMode
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetXattrs() string {
	if x != nil && x.Xattrs != nil {
		return *x.Xattrs
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetWorkers() []string {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ServerRetryTasksRequest) GetJobConcurrency() int32 {
	if x != nil && x.JobConcurrency != nil {
		return *x.JobConcurrency
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetRegionId() int32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetAppGroupId() int64 {
	if x != nil && x.AppGroupId != nil {
		return *x.AppGroupId
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetInstanceParameters() string {
	if x != nil && x.InstanceParameters != nil {
		return *x.InstanceParameters
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetUpstreamData() []*UpstreamData {
	if x != nil {
		return x.UpstreamData
	}
	return nil
}

func (x *ServerRetryTasksRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetTimeType() int32 {
	if x != nil && x.TimeType != nil {
		return *x.TimeType
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetTimeExpression() string {
	if x != nil && x.TimeExpression != nil {
		return *x.TimeExpression
	}
	return ""
}

func (x *ServerRetryTasksRequest) GetMaxAttempt() int32 {
	if x != nil && x.MaxAttempt != nil {
		return *x.MaxAttempt
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetAttempt() int32 {
	if x != nil && x.Attempt != nil {
		return *x.Attempt
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetWfInstanceId() int64 {
	if x != nil && x.WfInstanceId != nil {
		return *x.WfInstanceId
	}
	return 0
}

func (x *ServerRetryTasksRequest) GetRetryTaskEntity() []*RetryTaskEntity {
	if x != nil {
		return x.RetryTaskEntity
	}
	return nil
}

func (x *ServerRetryTasksRequest) GetJobName() string {
	if x != nil && x.JobName != nil {
		return *x.JobName
	}
	return ""
}

type ServerRetryTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerRetryTasksResponse fields.
const (
	Default_ServerRetryTasksResponse_Message = string("")
)

func (x *ServerRetryTasksResponse) Reset() {
	*x = ServerRetryTasksResponse{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRetryTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRetryTasksResponse) ProtoMessage() {}

func (x *ServerRetryTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRetryTasksResponse.ProtoReflect.Descriptor instead.
func (*ServerRetryTasksResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *ServerRetryTasksResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerRetryTasksResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerRetryTasksResponse_Message
}

// tail log
type ServerTailLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	TaskId        *int64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,def=1" json:"task_id,omitempty"`
	Num           *int32                 `protobuf:"varint,4,req,name=num" json:"num,omitempty"`
	ScheduleTime  *int64                 `protobuf:"varint,5,req,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerTailLogRequest fields.
const (
	Default_ServerTailLogRequest_TaskId = int64(1)
)

func (x *ServerTailLogRequest) Reset() {
	*x = ServerTailLogRequest{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTailLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTailLogRequest) ProtoMessage() {}

func (x *ServerTailLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTailLogRequest.ProtoReflect.Descriptor instead.
func (*ServerTailLogRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *ServerTailLogRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerTailLogRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerTailLogRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return Default_ServerTailLogRequest_TaskId
}

func (x *ServerTailLogRequest) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *ServerTailLogRequest) GetScheduleTime() int64 {
	if x != nil && x.ScheduleTime != nil {
		return *x.ScheduleTime
	}
	return 0
}

type ServerTailLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	Line          []string               `protobuf:"bytes,3,rep,name=line" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerTailLogResponse fields.
const (
	Default_ServerTailLogResponse_Message = string("")
)

func (x *ServerTailLogResponse) Reset() {
	*x = ServerTailLogResponse{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTailLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTailLogResponse) ProtoMessage() {}

func (x *ServerTailLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTailLogResponse.ProtoReflect.Descriptor instead.
func (*ServerTailLogResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *ServerTailLogResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerTailLogResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerTailLogResponse_Message
}

func (x *ServerTailLogResponse) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

// read log by lines
type ServerReadLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	TaskId        *int64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,def=1" json:"task_id,omitempty"`
	ScheduleTime  *int64                 `protobuf:"varint,4,req,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	Offset        *int64                 `protobuf:"varint,5,req,name=offset" json:"offset,omitempty"`
	Size          *int32                 `protobuf:"varint,6,req,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerReadLogRequest fields.
const (
	Default_ServerReadLogRequest_TaskId = int64(1)
)

func (x *ServerReadLogRequest) Reset() {
	*x = ServerReadLogRequest{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadLogRequest) ProtoMessage() {}

func (x *ServerReadLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadLogRequest.ProtoReflect.Descriptor instead.
func (*ServerReadLogRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *ServerReadLogRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerReadLogRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerReadLogRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return Default_ServerReadLogRequest_TaskId
}

func (x *ServerReadLogRequest) GetScheduleTime() int64 {
	if x != nil && x.ScheduleTime != nil {
		return *x.ScheduleTime
	}
	return 0
}

func (x *ServerReadLogRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ServerReadLogRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type ServerReadLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	Line          []string               `protobuf:"bytes,3,rep,name=line" json:"line,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	IsEnd         *bool                  `protobuf:"varint,5,req,name=is_end,json=isEnd" json:"is_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerReadLogResponse fields.
const (
	Default_ServerReadLogResponse_Message = string("")
)

func (x *ServerReadLogResponse) Reset() {
	*x = ServerReadLogResponse{}
	mi := &file_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadLogResponse) ProtoMessage() {}

func (x *ServerReadLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadLogResponse.ProtoReflect.Descriptor instead.
func (*ServerReadLogResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

func (x *ServerReadLogResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerReadLogResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerReadLogResponse_Message
}

func (x *ServerReadLogResponse) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *ServerReadLogResponse) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ServerReadLogResponse) GetIsEnd() bool {
	if x != nil && x.IsEnd != nil {
		return *x.IsEnd
	}
	return false
}

// read log by chars
type ServerReadLogCharsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	TaskId        *int64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,def=1" json:"task_id,omitempty"`
	ScheduleTime  *int64                 `protobuf:"varint,4,req,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	Offset        *int64                 `protobuf:"varint,5,req,name=offset" json:"offset,omitempty"`
	Size          *int32                 `protobuf:"varint,6,req,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerReadLogCharsRequest fields.
const (
	Default_ServerReadLogCharsRequest_TaskId = int64(1)
)

func (x *ServerReadLogCharsRequest) Reset() {
	*x = ServerReadLogCharsRequest{}
	mi := &file_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadLogCharsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadLogCharsRequest) ProtoMessage() {}

func (x *ServerReadLogCharsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadLogCharsRequest.ProtoReflect.Descriptor instead.
func (*ServerReadLogCharsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17}
}

func (x *ServerReadLogCharsRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerReadLogCharsRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerReadLogCharsRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return Default_ServerReadLogCharsRequest_TaskId
}

func (x *ServerReadLogCharsRequest) GetScheduleTime() int64 {
	if x != nil && x.ScheduleTime != nil {
		return *x.ScheduleTime
	}
	return 0
}

func (x *ServerReadLogCharsRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ServerReadLogCharsRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type ServerReadLogCharsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	Log           *string                `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	IsEnd         *bool                  `protobuf:"varint,5,opt,name=is_end,json=isEnd" json:"is_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerReadLogCharsResponse fields.
const (
	Default_ServerReadLogCharsResponse_Message = string("")
)

func (x *ServerReadLogCharsResponse) Reset() {
	*x = ServerReadLogCharsResponse{}
	mi := &file_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadLogCharsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadLogCharsResponse) ProtoMessage() {}

func (x *ServerReadLogCharsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadLogCharsResponse.ProtoReflect.Descriptor instead.
func (*ServerReadLogCharsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{18}
}

func (x *ServerReadLogCharsResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerReadLogCharsResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerReadLogCharsResponse_Message
}

func (x *ServerReadLogCharsResponse) GetLog() string {
	if x != nil && x.Log != nil {
		return *x.Log
	}
	return ""
}

func (x *ServerReadLogCharsResponse) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ServerReadLogCharsResponse) GetIsEnd() bool {
	if x != nil && x.IsEnd != nil {
		return *x.IsEnd
	}
	return false
}

// server check if worker is alive
type ServerCheckTaskMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobInstanceId *int64                 `protobuf:"varint,1,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCheckTaskMasterRequest) Reset() {
	*x = ServerCheckTaskMasterRequest{}
	mi := &file_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckTaskMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckTaskMasterRequest) ProtoMessage() {}

func (x *ServerCheckTaskMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckTaskMasterRequest.ProtoReflect.Descriptor instead.
func (*ServerCheckTaskMasterRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{19}
}

func (x *ServerCheckTaskMasterRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

type ServerCheckTaskMasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerCheckTaskMasterResponse fields.
const (
	Default_ServerCheckTaskMasterResponse_Message = string("")
)

func (x *ServerCheckTaskMasterResponse) Reset() {
	*x = ServerCheckTaskMasterResponse{}
	mi := &file_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckTaskMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckTaskMasterResponse) ProtoMessage() {}

func (x *ServerCheckTaskMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckTaskMasterResponse.ProtoReflect.Descriptor instead.
func (*ServerCheckTaskMasterResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{20}
}

func (x *ServerCheckTaskMasterResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerCheckTaskMasterResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerCheckTaskMasterResponse_Message
}

// thread dump
type ServerThreadDumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *int64                 `protobuf:"varint,1,req,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,2,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	TaskId        *int64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,def=1" json:"task_id,omitempty"`
	Line          *int32                 `protobuf:"varint,4,opt,name=line,def=20" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerThreadDumpRequest fields.
const (
	Default_ServerThreadDumpRequest_TaskId = int64(1)
	Default_ServerThreadDumpRequest_Line   = int32(20)
)

func (x *ServerThreadDumpRequest) Reset() {
	*x = ServerThreadDumpRequest{}
	mi := &file_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerThreadDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerThreadDumpRequest) ProtoMessage() {}

func (x *ServerThreadDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerThreadDumpRequest.ProtoReflect.Descriptor instead.
func (*ServerThreadDumpRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{21}
}

func (x *ServerThreadDumpRequest) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *ServerThreadDumpRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

func (x *ServerThreadDumpRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return Default_ServerThreadDumpRequest_TaskId
}

func (x *ServerThreadDumpRequest) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return Default_ServerThreadDumpRequest_Line
}

type ServerThreadDumpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	Line          []string               `protobuf:"bytes,3,rep,name=line" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerThreadDumpResponse fields.
const (
	Default_ServerThreadDumpResponse_Message = string("")
)

func (x *ServerThreadDumpResponse) Reset() {
	*x = ServerThreadDumpResponse{}
	mi := &file_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerThreadDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerThreadDumpResponse) ProtoMessage() {}

func (x *ServerThreadDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerThreadDumpResponse.ProtoReflect.Descriptor instead.
func (*ServerThreadDumpResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{22}
}

func (x *ServerThreadDumpResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerThreadDumpResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerThreadDumpResponse_Message
}

func (x *ServerThreadDumpResponse) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

// push log config
type ServerPushLogConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        *bool                  `protobuf:"varint,1,req,name=enable" json:"enable,omitempty"`
	Config        *string                `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Level         *string                `protobuf:"bytes,4,opt,name=level" json:"level,omitempty"`
	SlsAk         *string                `protobuf:"bytes,5,opt,name=sls_ak,json=slsAk" json:"sls_ak,omitempty"`
	SlsSk         *string                `protobuf:"bytes,6,opt,name=sls_sk,json=slsSk" json:"sls_sk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPushLogConfigRequest) Reset() {
	*x = ServerPushLogConfigRequest{}
	mi := &file_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushLogConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushLogConfigRequest) ProtoMessage() {}

func (x *ServerPushLogConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushLogConfigRequest.ProtoReflect.Descriptor instead.
func (*ServerPushLogConfigRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{23}
}

func (x *ServerPushLogConfigRequest) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

func (x *ServerPushLogConfigRequest) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

func (x *ServerPushLogConfigRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ServerPushLogConfigRequest) GetLevel() string {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ""
}

func (x *ServerPushLogConfigRequest) GetSlsAk() string {
	if x != nil && x.SlsAk != nil {
		return *x.SlsAk
	}
	return ""
}

func (x *ServerPushLogConfigRequest) GetSlsSk() string {
	if x != nil && x.SlsSk != nil {
		return *x.SlsSk
	}
	return ""
}

type ServerPushLogConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerPushLogConfigResponse fields.
const (
	Default_ServerPushLogConfigResponse_Message = string("")
)

func (x *ServerPushLogConfigResponse) Reset() {
	*x = ServerPushLogConfigResponse{}
	mi := &file_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushLogConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushLogConfigResponse) ProtoMessage() {}

func (x *ServerPushLogConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushLogConfigResponse.ProtoReflect.Descriptor instead.
func (*ServerPushLogConfigResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{24}
}

func (x *ServerPushLogConfigResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerPushLogConfigResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerPushLogConfigResponse_Message
}

// Sync worker k8s job
type ServerSyncK8SJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppGroupId    *int64                 `protobuf:"varint,1,opt,name=app_group_id,json=appGroupId" json:"app_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSyncK8SJobRequest) Reset() {
	*x = ServerSyncK8SJobRequest{}
	mi := &file_server_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSyncK8SJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSyncK8SJobRequest) ProtoMessage() {}

func (x *ServerSyncK8SJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSyncK8SJobRequest.ProtoReflect.Descriptor instead.
func (*ServerSyncK8SJobRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{25}
}

func (x *ServerSyncK8SJobRequest) GetAppGroupId() int64 {
	if x != nil && x.AppGroupId != nil {
		return *x.AppGroupId
	}
	return 0
}

type ServerSyncK8SJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	JobYaml       []string               `protobuf:"bytes,3,rep,name=jobYaml" json:"jobYaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerSyncK8SJobResponse fields.
const (
	Default_ServerSyncK8SJobResponse_Message = string("")
)

func (x *ServerSyncK8SJobResponse) Reset() {
	*x = ServerSyncK8SJobResponse{}
	mi := &file_server_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSyncK8SJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSyncK8SJobResponse) ProtoMessage() {}

func (x *ServerSyncK8SJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSyncK8SJobResponse.ProtoReflect.Descriptor instead.
func (*ServerSyncK8SJobResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{26}
}

func (x *ServerSyncK8SJobResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerSyncK8SJobResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerSyncK8SJobResponse_Message
}

func (x *ServerSyncK8SJobResponse) GetJobYaml() []string {
	if x != nil {
		return x.JobYaml
	}
	return nil
}

// Sync worker k8s cron job
type ServerSyncK8SCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppGroupId    *int64                 `protobuf:"varint,1,opt,name=app_group_id,json=appGroupId" json:"app_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSyncK8SCronJobRequest) Reset() {
	*x = ServerSyncK8SCronJobRequest{}
	mi := &file_server_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSyncK8SCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSyncK8SCronJobRequest) ProtoMessage() {}

func (x *ServerSyncK8SCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSyncK8SCronJobRequest.ProtoReflect.Descriptor instead.
func (*ServerSyncK8SCronJobRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{27}
}

func (x *ServerSyncK8SCronJobRequest) GetAppGroupId() int64 {
	if x != nil && x.AppGroupId != nil {
		return *x.AppGroupId
	}
	return 0
}

type ServerSyncK8SCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	CronJobYaml   []string               `protobuf:"bytes,3,rep,name=cronJobYaml" json:"cronJobYaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerSyncK8SCronJobResponse fields.
const (
	Default_ServerSyncK8SCronJobResponse_Message = string("")
)

func (x *ServerSyncK8SCronJobResponse) Reset() {
	*x = ServerSyncK8SCronJobResponse{}
	mi := &file_server_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSyncK8SCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSyncK8SCronJobResponse) ProtoMessage() {}

func (x *ServerSyncK8SCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSyncK8SCronJobResponse.ProtoReflect.Descriptor instead.
func (*ServerSyncK8SCronJobResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{28}
}

func (x *ServerSyncK8SCronJobResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerSyncK8SCronJobResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerSyncK8SCronJobResponse_Message
}

func (x *ServerSyncK8SCronJobResponse) GetCronJobYaml() []string {
	if x != nil {
		return x.CronJobYaml
	}
	return nil
}

// Server Callback calendar
type ServerCallbackCalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processor     *string                `protobuf:"bytes,1,req,name=processor" json:"processor,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	JobInstanceId *int64                 `protobuf:"varint,3,req,name=job_instance_id,json=jobInstanceId" json:"job_instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCallbackCalendarRequest) Reset() {
	*x = ServerCallbackCalendarRequest{}
	mi := &file_server_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCallbackCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCallbackCalendarRequest) ProtoMessage() {}

func (x *ServerCallbackCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCallbackCalendarRequest.ProtoReflect.Descriptor instead.
func (*ServerCallbackCalendarRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{29}
}

func (x *ServerCallbackCalendarRequest) GetProcessor() string {
	if x != nil && x.Processor != nil {
		return *x.Processor
	}
	return ""
}

func (x *ServerCallbackCalendarRequest) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ServerCallbackCalendarRequest) GetJobInstanceId() int64 {
	if x != nil && x.JobInstanceId != nil {
		return *x.JobInstanceId
	}
	return 0
}

type ServerCallbackCalendarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,def=" json:"message,omitempty"`
	Result        *bool                  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ServerCallbackCalendarResponse fields.
const (
	Default_ServerCallbackCalendarResponse_Message = string("")
)

func (x *ServerCallbackCalendarResponse) Reset() {
	*x = ServerCallbackCalendarResponse{}
	mi := &file_server_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCallbackCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCallbackCalendarResponse) ProtoMessage() {}

func (x *ServerCallbackCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCallbackCalendarResponse.ProtoReflect.Descriptor instead.
func (*ServerCallbackCalendarResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{30}
}

func (x *ServerCallbackCalendarResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ServerCallbackCalendarResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return Default_ServerCallbackCalendarResponse_Message
}

func (x *ServerCallbackCalendarResponse) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12 schedulerx_worker.internal.proto\x1a\fcommon.proto\"\xda\b\n" +
	"\x1eServerSubmitJobInstanceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12#\n" +
	"\rschedule_time\x18\x03 \x02(\x03R\fscheduleTime\x12\x1b\n" +
	"\tdata_time\x18\x04 \x02(\x03R\bdataTime\x12\x19\n" +
	"\bjob_type\x18\x05 \x02(\tR\ajobType\x12!\n" +
	"\fexecute_mode\x18\x06 \x02(\tR\vexecuteMode\x12\x18\n" +
	"\acontent\x18\a \x02(\tR\acontent\x12\x12\n" +
	"\x04user\x18\b \x02(\tR\x04user\x12\x16\n" +
	"\x06xattrs\x18\t \x01(\tR\x06xattrs\x12\x1e\n" +
	"\n" +
	"parameters\x18\n" +
	" \x01(\tR\n" +
	"parameters\x12\x18\n" +
	"\aworkers\x18\v \x03(\tR\aworkers\x12'\n" +
	"\x0fjob_concurrency\x18\f \x02(\x05R\x0ejobConcurrency\x12\x1b\n" +
	"\tregion_id\x18\r \x02(\x05R\bregionId\x12 \n" +
	"\fapp_group_id\x18\x0e \x02(\x03R\n" +
	"appGroupId\x12/\n" +
	"\x13instance_parameters\x18\x0f \x01(\tR\x12instanceParameters\x12R\n" +
	"\fupstreamData\x18\x10 \x03(\v2..schedulerx_worker.internal.proto.UpstreamDataR\fupstreamData\x12\x19\n" +
	"\bgroup_id\x18\x11 \x01(\tR\agroupId\x12\x1b\n" +
	"\ttime_type\x18\x12 \x01(\x05R\btimeType\x12'\n" +
	"\x0ftime_expression\x18\x13 \x01(\tR\x0etimeExpression\x12\x1f\n" +
	"\vmax_attempt\x18\x14 \x01(\x05R\n" +
	"maxAttempt\x12\x18\n" +
	"\aattempt\x18\x15 \x01(\x05R\aattempt\x12$\n" +
	"\x0ewf_instance_id\x18\x16 \x01(\x03R\fwfInstanceId\x12\x19\n" +
	"\bjob_name\x18\x17 \x01(\tR\ajobName\x12\x1c\n" +
	"\tnamespace\x18\x18 \x01(\tR\tnamespace\x12!\n" +
	"\ftrigger_type\x18\x19 \x01(\x05R\vtriggerType\x12.\n" +
	"\x13route_strategy_type\x18\x1a \x01(\x05R\x11routeStrategyType\x124\n" +
	"\x16route_strategy_content\x18\x1b \x01(\tR\x14routeStrategyContent\x12l\n" +
	"\x16label_worker_addrs_map\x18\x1c \x03(\v27.schedulerx_worker.internal.proto.LabelWorkerAddrsEntryR\x13labelWorkerAddrsMap\x12\x1a\n" +
	"\btemplate\x18\x1d \x01(\tR\btemplate\"W\n" +
	"\x1fServerSubmitJobInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\xc2\x02\n" +
	"\x1cServerKillJobInstanceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1f\n" +
	"\vdestory_job\x18\x04 \x01(\bR\n" +
	"destoryJob\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12\x16\n" +
	"\x06xattrs\x18\b \x01(\tR\x06xattrs\x12!\n" +
	"\fexecute_mode\x18\t \x01(\tR\vexecuteMode\x12 \n" +
	"\fapp_group_id\x18\n" +
	" \x01(\x03R\n" +
	"appGroupId\"U\n" +
	"\x1dServerKillJobInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\xc1\x01\n" +
	"\x15ServerKillTaskRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x17\n" +
	"\atask_id\x18\x03 \x02(\x03R\x06taskId\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1b\n" +
	"\tworker_id\x18\x05 \x02(\tR\bworkerId\x12\x1f\n" +
	"\vworker_addr\x18\x06 \x02(\tR\n" +
	"workerAddr\"N\n" +
	"\x16ServerKillTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"e\n" +
	"\x19ServerCreateRegionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x02(\tR\vdescription\x12\x12\n" +
	"\x04user\x18\x03 \x02(\tR\x04user\"R\n" +
	"\x1aServerCreateRegionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\x85\x01\n" +
	"\x16ServerCreateAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x02(\tR\vdescription\x12\x1b\n" +
	"\tregion_id\x18\x03 \x02(\x05R\bregionId\x12\x18\n" +
	"\acreator\x18\x04 \x02(\tR\acreator\"O\n" +
	"\x17ServerCreateAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\x87\x01\n" +
	"\x0fRetryTaskEntity\x12\x17\n" +
	"\atask_id\x18\x01 \x02(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x02(\tR\btaskName\x12\x1f\n" +
	"\vworker_addr\x18\x03 \x02(\tR\n" +
	"workerAddr\x12\x1d\n" +
	"\n" +
	"old_status\x18\x04 \x02(\x05R\toldStatus\"\x81\a\n" +
	"\x17ServerRetryTasksRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12#\n" +
	"\rschedule_time\x18\x03 \x02(\x03R\fscheduleTime\x12\x1b\n" +
	"\tdata_time\x18\x04 \x02(\x03R\bdataTime\x12\x19\n" +
	"\bjob_type\x18\x05 \x02(\tR\ajobType\x12!\n" +
	"\fexecute_mode\x18\x06 \x02(\tR\vexecuteMode\x12\x18\n" +
	"\acontent\x18\a \x02(\tR\acontent\x12\x12\n" +
	"\x04user\x18\b \x02(\tR\x04user\x12\x16\n" +
	"\x06xattrs\x18\t \x01(\tR\x06xattrs\x12\x1e\n" +
	"\n" +
	"parameters\x18\n" +
	" \x01(\tR\n" +
	"parameters\x12\x18\n" +
	"\aworkers\x18\v \x03(\tR\aworkers\x12'\n" +
	"\x0fjob_concurrency\x18\f \x02(\x05R\x0ejobConcurrency\x12\x1b\n" +
	"\tregion_id\x18\r \x02(\x05R\bregionId\x12 \n" +
	"\fapp_group_id\x18\x0e \x02(\x03R\n" +
	"appGroupId\x12/\n" +
	"\x13instance_parameters\x18\x0f \x01(\tR\x12instanceParameters\x12R\n" +
	"\fupstreamData\x18\x10 \x03(\v2..schedulerx_worker.internal.proto.UpstreamDataR\fupstreamData\x12\x19\n" +
	"\bgroup_id\x18\x11 \x01(\tR\agroupId\x12\x1b\n" +
	"\ttime_type\x18\x12 \x01(\x05R\btimeType\x12'\n" +
	"\x0ftime_expression\x18\x13 \x01(\tR\x0etimeExpression\x12\x1f\n" +
	"\vmax_attempt\x18\x14 \x01(\x05R\n" +
	"maxAttempt\x12\x18\n" +
	"\aattempt\x18\x15 \x01(\x05R\aattempt\x12$\n" +
	"\x0ewf_instance_id\x18\x16 \x01(\x03R\fwfInstanceId\x12]\n" +
	"\x11retry_task_entity\x18\x17 \x03(\v21.schedulerx_worker.internal.proto.RetryTaskEntityR\x0fretryTaskEntity\x12\x19\n" +
	"\bjob_name\x18\x18 \x01(\tR\ajobName\"P\n" +
	"\x18ServerRetryTasksResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\xa8\x01\n" +
	"\x14ServerTailLogRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x1a\n" +
	"\atask_id\x18\x03 \x01(\x03:\x011R\x06taskId\x12\x10\n" +
	"\x03num\x18\x04 \x02(\x05R\x03num\x12#\n" +
	"\rschedule_time\x18\x05 \x02(\x03R\fscheduleTime\"a\n" +
	"\x15ServerTailLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x03(\tR\x04line\"\xc2\x01\n" +
	"\x14ServerReadLogRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x1a\n" +
	"\atask_id\x18\x03 \x01(\x03:\x011R\x06taskId\x12#\n" +
	"\rschedule_time\x18\x04 \x02(\x03R\fscheduleTime\x12\x16\n" +
	"\x06offset\x18\x05 \x02(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x06 \x02(\x05R\x04size\"\x90\x01\n" +
	"\x15ServerReadLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x03(\tR\x04line\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x15\n" +
	"\x06is_end\x18\x05 \x02(\bR\x05isEnd\"\xc7\x01\n" +
	"\x19ServerReadLogCharsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x1a\n" +
	"\atask_id\x18\x03 \x01(\x03:\x011R\x06taskId\x12#\n" +
	"\rschedule_time\x18\x04 \x02(\x03R\fscheduleTime\x12\x16\n" +
	"\x06offset\x18\x05 \x02(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x06 \x02(\x05R\x04size\"\x93\x01\n" +
	"\x1aServerReadLogCharsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x10\n" +
	"\x03log\x18\x03 \x01(\tR\x03log\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x15\n" +
	"\x06is_end\x18\x05 \x01(\bR\x05isEnd\"F\n" +
	"\x1cServerCheckTaskMasterRequest\x12&\n" +
	"\x0fjob_instance_id\x18\x01 \x02(\x03R\rjobInstanceId\"U\n" +
	"\x1dServerCheckTaskMasterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\"\x8c\x01\n" +
	"\x17ServerThreadDumpRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x02(\x03R\x05jobId\x12&\n" +
	"\x0fjob_instance_id\x18\x02 \x02(\x03R\rjobInstanceId\x12\x1a\n" +
	"\atask_id\x18\x03 \x01(\x03:\x011R\x06taskId\x12\x16\n" +
	"\x04line\x18\x04 \x01(\x05:\x0220R\x04line\"d\n" +
	"\x18ServerThreadDumpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x03(\tR\x04line\"\xa4\x01\n" +
	"\x1aServerPushLogConfigRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x02(\bR\x06enable\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x15\n" +
	"\x06sls_ak\x18\x05 \x01(\tR\x05slsAk\x12\x15\n" +
	"\x06sls_sk\x18\x06 \x01(\tR\x05slsSk\"S\n" +
	"\x1bServerPushLogConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\";\n" +
	"\x17ServerSyncK8sJobRequest\x12 \n" +
	"\fapp_group_id\x18\x01 \x01(\x03R\n" +
	"appGroupId\"j\n" +
	"\x18ServerSyncK8sJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x18\n" +
	"\ajobYaml\x18\x03 \x03(\tR\ajobYaml\"?\n" +
	"\x1bServerSyncK8sCronJobRequest\x12 \n" +
	"\fapp_group_id\x18\x01 \x01(\x03R\n" +
	"appGroupId\"v\n" +
	"\x1cServerSyncK8sCronJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12 \n" +
	"\vcronJobYaml\x18\x03 \x03(\tR\vcronJobYaml\"\x83\x01\n" +
	"\x1dServerCallbackCalendarRequest\x12\x1c\n" +
	"\tprocessor\x18\x01 \x02(\tR\tprocessor\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x02(\x03R\ttimestamp\x12&\n" +
	"\x0fjob_instance_id\x18\x03 \x02(\x03R\rjobInstanceId\"n\n" +
	"\x1eServerCallbackCalendarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\t:\x00R\amessage\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06resultB\x0eZ\f./schedulerx"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_server_proto_goTypes = []any{
	(*ServerSubmitJobInstanceRequest)(nil),  // 0: schedulerx_worker.internal.proto.ServerSubmitJobInstanceRequest
	(*ServerSubmitJobInstanceResponse)(nil), // 1: schedulerx_worker.internal.proto.ServerSubmitJobInstanceResponse
	(*ServerKillJobInstanceRequest)(nil),    // 2: schedulerx_worker.internal.proto.ServerKillJobInstanceRequest
	(*ServerKillJobInstanceResponse)(nil),   // 3: schedulerx_worker.internal.proto.ServerKillJobInstanceResponse
	(*ServerKillTaskRequest)(nil),           // 4: schedulerx_worker.internal.proto.ServerKillTaskRequest
	(*ServerKillTaskResponse)(nil),          // 5: schedulerx_worker.internal.proto.ServerKillTaskResponse
	(*ServerCreateRegionRequest)(nil),       // 6: schedulerx_worker.internal.proto.ServerCreateRegionRequest
	(*ServerCreateRegionResponse)(nil),      // 7: schedulerx_worker.internal.proto.ServerCreateRegionResponse
	(*ServerCreateAppRequest)(nil),          // 8: schedulerx_worker.internal.proto.ServerCreateAppRequest
	(*ServerCreateAppResponse)(nil),         // 9: schedulerx_worker.internal.proto.ServerCreateAppResponse
	(*RetryTaskEntity)(nil),                 // 10: schedulerx_worker.internal.proto.RetryTaskEntity
	(*ServerRetryTasksRequest)(nil),         // 11: schedulerx_worker.internal.proto.ServerRetryTasksRequest
	(*ServerRetryTasksResponse)(nil),        // 12: schedulerx_worker.internal.proto.ServerRetryTasksResponse
	(*ServerTailLogRequest)(nil),            // 13: schedulerx_worker.internal.proto.ServerTailLogRequest
	(*ServerTailLogResponse)(nil),           // 14: schedulerx_worker.internal.proto.ServerTailLogResponse
	(*ServerReadLogRequest)(nil),            // 15: schedulerx_worker.internal.proto.ServerReadLogRequest
	(*ServerReadLogResponse)(nil),           // 16: schedulerx_worker.internal.proto.ServerReadLogResponse
	(*ServerReadLogCharsRequest)(nil),       // 17: schedulerx_worker.internal.proto.ServerReadLogCharsRequest
	(*ServerReadLogCharsResponse)(nil),      // 18: schedulerx_worker.internal.proto.ServerReadLogCharsResponse
	(*ServerCheckTaskMasterRequest)(nil),    // 19: schedulerx_worker.internal.proto.ServerCheckTaskMasterRequest
	(*ServerCheckTaskMasterResponse)(nil),   // 20: schedulerx_worker.internal.proto.ServerCheckTaskMasterResponse
	(*ServerThreadDumpRequest)(nil),         // 21: schedulerx_worker.internal.proto.ServerThreadDumpRequest
	(*ServerThreadDumpResponse)(nil),        // 22: schedulerx_worker.internal.proto.ServerThreadDumpResponse
	(*ServerPushLogConfigRequest)(nil),      // 23: schedulerx_worker.internal.proto.ServerPushLogConfigRequest
	(*ServerPushLogConfigResponse)(nil),     // 24: schedulerx_worker.internal.proto.ServerPushLogConfigResponse
	(*ServerSyncK8SJobRequest)(nil),         // 25: schedulerx_worker.internal.proto.ServerSyncK8sJobRequest
	(*ServerSyncK8SJobResponse)(nil),        // 26: schedulerx_worker.internal.proto.ServerSyncK8sJobResponse
	(*ServerSyncK8SCronJobRequest)(nil),     // 27: schedulerx_worker.internal.proto.ServerSyncK8sCronJobRequest
	(*ServerSyncK8SCronJobResponse)(nil),    // 28: schedulerx_worker.internal.proto.ServerSyncK8sCronJobResponse
	(*ServerCallbackCalendarRequest)(nil),   // 29: schedulerx_worker.internal.proto.ServerCallbackCalendarRequest
	(*ServerCallbackCalendarResponse)(nil),  // 30: schedulerx_worker.internal.proto.ServerCallbackCalendarResponse
	(*UpstreamData)(nil),                    // 31: schedulerx_worker.internal.proto.UpstreamData
	(*LabelWorkerAddrsEntry)(nil),           // 32: schedulerx_worker.internal.proto.LabelWorkerAddrsEntry
}
var file_server_proto_depIdxs = []int32{
	31, // 0: schedulerx_worker.internal.proto.ServerSubmitJobInstanceRequest.upstreamData:type_name -> schedulerx_worker.internal.proto.UpstreamData
	32, // 1: schedulerx_worker.internal.proto.ServerSubmitJobInstanceRequest.label_worker_addrs_map:type_name -> schedulerx_worker.internal.proto.LabelWorkerAddrsEntry
	31, // 2: schedulerx_worker.internal.proto.ServerRetryTasksRequest.upstreamData:type_name -> schedulerx_worker.internal.proto.UpstreamData
	10, // 3: schedulerx_worker.internal.proto.ServerRetryTasksRequest.retry_task_entity:type_name -> schedulerx_worker.internal.proto.RetryTaskEntity
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
